### ISSUE TITLE
ProjectE tools aren't recognized as valid tools

### ISSUE THREAD

**Issue by heatseeker0** [sinkillerj/ProjectE#406] opened 2015-01-21 10:33 UTC
Morning Star works well with all other ore types I've tried. But when mining Yellorium ore from Big Reactors nothing drops. Other pickaxe types, for example the ones from Tinker's Construct, work fine in the same modpack so I'm assuming it's a ProjectE issue.

**Comment by sinkillerj** [comment] 2015-01-21 11:08
Testing against dev13 of ProjectE and BigReactors-0.4.1A2 I am unable to reproduce this issue. I have tried both the right click and left click functions, as well as charging, each time I get the correct amount of Yellorium ore (it drops itself much like iron and gold).

**Comment by heatseeker0** [comment] 2015-01-21 19:58
Upon further testing with sinkillerj we noticed that:

1. This is not limited to Yellorium. About half the ores display this issue, including nether quartz ore.
2. It is in fact related to having Iguana Tinker Tweaks enabled and set to disable vanilla tools.

The actual issue comes from the fact that none of ProjectE tools are recognized (by none of the mods I've tested with) as valid tools. Easiest this can be determined is by installing Iguana and typing /dumpTools in singleplayer.

This prevents using them in any form of automation that accepts only valid tools (of a specific type).

**Comment by MaPePeR** [comment] 2015-10-03 21:02
This is caused by Iguana Tweaks adding more Harvest Levels. Our Pickaxe [returns `4`](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java#L83-L91). With Iguana Tweaks [harvestlevel = `4` means bronze](https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/harvestlevels/TinkerMaterialTweaks.java#L25-L35), so our tools are not strong enough to break some ores. (I tested with Shiny and Certus Quartz).

We could just bump this up to 9/Manyullyn. Nothing should break when the harvest level of our tool is bigger than anything that is available, right?

Also we might need to change [this line](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java#L98) from

```java
if (canHarvestBlock(block, stack) 
    || ForgeHooks.canToolHarvestBlock(block, metadata, stack))
```
to
```java
if ((canHarvestBlock(block, stack) && getHarvestLevel(stack, block.getHarvestTool(metadata)) >= block.getHarvestLevel(metadata)) 
    || ForgeHooks.canToolHarvestBlock(block, metadata, stack))
```

so our tools get slower when they cannot break the block because of harvestlevel.

**Comment by pupnewfster** [comment] 2020-02-17 23:26
Closing this as in 1.14 I rewrote the tools to extend the proper vanilla classes and the like. So this shouldn't be an issue in 1.14/1.15

**Closed by pupnewfster** 2020-02-17 23:26 UTC
Labels: enhancement
