### ISSUE TITLE
[1.14.4] All EMC and knowledge lost on death, even with keepInventory on

### ISSUE THREAD

**Issue by Seiris-Frotuen** [sinkillerj/ProjectE#1961] opened 2020-01-26 14:00 UTC
Exact ProjectE version: ProjectE-1.14.4-PE1.0.1B
Exact Forge version: forge-28.1.116
Steps to reproduce:

1. Update to ProjectE-1.14.4-PE1.0.1B from a previous version.
2. Die while possessing knowledge/EMC.

What I expected to happen: 
EMC and knowledge should be preserved.

What happened instead:
All EMC and knowledge is lost upon death. I did not have to switch dimensions for this to happen, and I am unsure if opening the world to LAN might have affected it in some way. The problem affects all of my saves, including fresh ones.

**Comment by pupnewfster** [comment] 2020-02-18 01:19
I am not able to reproduce this, could you upload your latest log file from after you die and the knowledge is lost?

**Comment by Seiris-Frotuen** [comment] 2020-02-19 01:55
Certainly. Attached is the latest log.

[latest.log](https://github.com/sinkillerj/ProjectE/files/4222728/latest.log)

**Comment by pupnewfster** [comment] 2020-02-19 02:03
Are you able to reproduce this issue with *just* ProjectE installed. Given it is a bit hard to tell what is going on in your latest log, as there are *a lot* of errors being printed, and I am not sure if some other mod erroring is ending up putting the player entity in an invalid state making it so that we are unable to properly clone the player data.

**Comment by Seiris-Frotuen** [comment] 2020-02-21 01:31
After a bit of messing about, I found the culprit. Disabling this mod got rid of the error for me.

https://www.curseforge.com/minecraft/mc-mods/angel-of-vengeance

**Comment by pupnewfster** [comment] 2020-02-21 02:00
I would go ahead and report the issue to their issue tracker, as it is likely they are somehow clearing the player's capabilities potentially breaking lots of mods not just ProjectE.

**Comment by Seiris-Frotuen** [comment] 2020-02-22 04:44
It appears there already is an open issue related to this -
https://github.com/Tamaized/AoV/issues/146#issue-551963019

i actually dunno what hes talking about but the word 'capabilities' was mentioned so i just assumed it was related to this issue

**Comment by pupnewfster** [comment] 2020-02-22 04:45
Ya from the brief description if that is what he is doing that would probably break this. Going to go ahead and close this though given there is nothing on ProjectE's end that can be done.

**Closed by pupnewfster** 2020-02-22 04:45 UTC
