### ISSUE TITLE
API Wishlist

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#807] opened 2015-06-26 00:19 UTC
I just started taking another look at the API, and started on some things.

Track progress here: https://github.com/williewillus/ProjectE/tree/api

So far the wishlist is:
* Register custom emc values
* Query whether an object has an emc value
* Query an object's exact emc value
* Events for when player-specific emc or knowledge is modified.
* Events for when the emc map is remapped (for individual items as well)
* Query player knowledge online
* Query player knowledge offline
* Set and remove player knowledge online
* Set and remove player knowledge offline (risky :/)

**Comment by sinkillerj** [comment] 2015-06-26 01:33
Duplicate of #591, but as it got a lil off topic this can be the new issue.

**Comment by TomeWyrm** [comment] 2015-06-26 16:37
If possible, could you give us a per-mod blacklist on the ability of any mod to set/change EMC values for itself and other mods?

Sinkiller put this in the original message for #591 but I'm including it here because I do think it will be immensely helpful.

"Mods that attempt to modify EMC values in any way, adding, removing, etc, are automatically added to a config file where the user can deny that mods permission to do so. Ideally two config options per mod, allow modify self, and allow modify other mod id's."

Also please make the user-editable config file override any and all other methods of assigning EMC. No automated system is perfect, and modded MC is full of odd loopholes and shortcuts that no author could honestly forsee.

**Comment by MaPePeR** [comment] 2015-06-26 17:09
TomeWyrm: i remember implementing that. i think thats already included...

**Comment by williewillus** [comment] 2015-06-27 01:15
Also, I'm wondering if any changes / unifications to the emc data type want to be made here, because I want to push an API that will not change that much. It's doubles, longs, and ints in various places.

**Comment by sinkillerj** [comment] 2015-06-27 01:51
Is migration the only issue with going larger than a double? What would fail to migrate? I'm not that concerned about a klein star loosing a charge.

**Comment by williewillus** [comment] 2015-06-27 03:09
If we wanted to migrate off of double (I was thinking smaller, but same thing for larger too), we would have to 

1. Write for TE's that migrates the double to whatever else it is and save that new thing to NBT
2. All power items that store EMC will need migration code to read the double from NBT and resave it to something else. I imagine some people would be very pissed if their kleins lost all their stored emc :p 
3. All player-related emc. So that means the transmutation gui stuff that I just got shiny migration code out for will need another migration layer on top of that, which I'm already trying to imagine - it'll be a nightmare in terms of code cleanliness.

I'd rather just stay on double.

**Comment by MaPePeR** [comment] 2015-06-27 07:39
> any objections against moving everything else (which is only the tooltip renderer basically) to double?

Yes. Especially because we only use integer values we should use integers or longs. 
Doubles don't work like "we only use the part before the dot, ask we should be fine". 

Doubles and floats turn 123456 into 1.23456*10^5 which will  then have the same problems as all the other floats and doubles. 
(the. 23456 part is **approximated** using 2^-1 + 2^-2 + 2^-3+....)

**Comment by williewillus** [comment] 2015-06-27 16:36
So much migration code needs to be written though :(

**Comment by williewillus** [comment] 2015-07-16 13:54
@MaPePeR also, we talked a long time ago about allowing modders to register their own EMC mappers, is that still a viable thing?

**Comment by MaPePeR** [comment] 2015-07-16 13:58
@williewillus with #851 i have a better feeling about that.
Sure, that would be a viable option, but at the moment i don't see a big demand for that.
And it requires some restructuring:
The problem is, that mappers may overwrite values, so in theory we would have to add a priority list.

**Comment by williewillus** [comment] 2015-07-16 14:02
alright, we'll wait till after this api goes in first for that

**Comment by sinkillerj** [comment] 2015-07-16 14:52
A mod should never need to implement a mapper directly into our mod, all calculation can be done on their side and simply sent to us.

That being said we do still need registration for (list of input items) = (output item) so ProjectE can do smart calculation for recipes we cannot read, for example a mod could use this to register machine outputs, this is something I need atm for PE-addons. If nothing else I can get this implemented before we push the new api into a release.

**Comment by MaPePeR** [comment] 2015-07-16 14:56
> That being said we do still need registration for (list of input items) = (output item) so ProjectE can do smart calculation for recipes we cannot read,

I think thats exaclty what we meant by 'mapper'. For me a 'mapper' is something that adds these recipes.

**Comment by williewillus** [comment] 2015-07-16 21:51
Yeah I meant mapper as an "Something that makes us aware of how to read their recipes / the fact that they exist"
The actual number crunching is still on us.
It's for mods that use custom IRecipes for everything >.>

**Closed** 2015-07-30 21:13 UTC
