### ISSUE TITLE
Crash with dark matter pick

### ISSUE THREAD

**Issue by Firehead94** [sinkillerj/ProjectE#1130] opened 2016-01-03 04:46 UTC
When right clicking with Dark Matter Pick in the spawn chunk to vein mine (when protected) crashes the server. Reproduced twice.

**Comment by MaPePeR** [comment] 2016-01-03 08:08
Version of ProjectE? I thought this is fixed in the latest release... 

Crash log? 

Single or multiplayer? 

I think it is a duplicate of another issue.

**Comment by Firehead94** [comment] 2016-01-03 09:47
You know what, it may have been, I'd have to check. I didn't even think about it to be honest. Just noticed it when stress testing the Tekkit Legends pack trying to find out what's causing some tps issues. I looked through the open issues and didn't see, forgot to check versions. Sorry about that.

**Comment by Alexismachina** [comment] 2016-01-04 20:06
Still. log ?

**Comment by Firehead94** [comment] 2016-01-07 03:51
Cant find it but when we updated the mod, it stopped doing it.

**Comment by Alexismachina** [comment] 2016-01-07 20:11
@williewillus close this ?

**Closed** 2016-01-27 02:28 UTC
