### ISSUE TITLE
EMC value and Table data lost upon re-entering Overworld (All The Mods 4)

### ISSUE THREAD

**Issue by Th3BlackLotus** [sinkillerj/ProjectE#1951] opened 2020-01-01 22:20 UTC
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.14.4-PE1.0.0B

Exact Forge version:Forge-28.1.104

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.Using the portal in The End to return to the over world

What I expected to happen:Transmutation Table to retain data, and bring up items learned and EMC value

What happened instead: The table is wiped clean of all items, an the EMC value is reset to 0.  Any item added to the table adds its correct EMC value, and gives the "learned" message.

**Comment by Th3BlackLotus** [comment] 2020-01-01 22:20
I am aware that Project E is not part of the ATM4 modpack.  I added it for fun and functionality.  Going to the end, and teleporting back by using waypoints does not clear the EMC data, just the End portal BACK to the overworld.

**Comment by pupnewfster** [comment] 2020-01-01 22:33
Duplicate of #1943 though if you update to the latest forge for 1.14, 28.1.111 it should be fixed.

**Closed by pupnewfster** 2020-01-01 22:33 UTC
