### ISSUE TITLE
Gem Boots warp FOV even with FOV Effects disabled

### ISSUE THREAD

**Issue by dylithian** [sinkillerj/ProjectE#2278] opened 2023-05-19 01:45 UTC
Exact ProjectE version: ProjectE-1.19.2-PE1.0.1B

Exact Forge version: forge-1.19.2-43.2.8

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
Does not crash.

Steps to reproduce:

1. Disable FOV Effects in Video Settings
2. Craft Gem Boots
3. Equip Gem Boots
4. Notice that FOV changes (rather dramatically, if you ask me)

What I expected to happen:
FOV to remain unchanged when equipping the boots

What happened instead:
FOV changes when the boots are equipped

Images for reference:

No boots worn:
![image](https://github.com/sinkillerj/ProjectE/assets/64990317/37e145ab-21c6-4240-ab78-f453955cc089)

Freshly EMC-created boots worn:
![image](https://github.com/sinkillerj/ProjectE/assets/64990317/54ded314-5809-4b80-abb1-e36d62f99582)

**Comment by pupnewfster** [comment] 2023-10-26 19:08
Duplicate of #2237

**Closed as completed by pupnewfster** 2023-10-26 19:08 UTC
