### ISSUE TITLE
Crash with ProjectE + Baubles

### ISSUE THREAD

**Issue by juniorjunior** [sinkillerj/ProjectE#672] opened 2015-04-23 15:00 UTC
ProjectE 1.4.4
Baubles 1.0.1.10
Forge 1.7.10_1381
Crash report: http://pastebin.com/Bb14KSR0

Placing SwiftWolf's Rending Gale into a Baubles ring slot crashes the client. This bug was introduced with ProjectE 1.4.4 as earlier versions (<=1.4.3.1) do not crash.

**Comment by MaPePeR** [comment] 2015-04-23 16:20
Duplicate #669

**Comment by williewillus** [comment] 2015-04-23 16:20
Duplicate of #655 and resolved by #659. Please search the tracker before reporting, but thanks for the report!

**Closed** 2015-04-23 16:20 UTC

**Comment by juniorjunior** [comment] 2015-04-23 17:20
Fair enough. Should have searched. Is there a Jenkins/build server for dev versions or do we just wait on a release?

**Comment by MaPePeR** [comment] 2015-04-23 17:30
You wait for a release. there are no dev versions for your own safety, i think
