### ISSUE TITLE
crashes when trying to use mercurial eye

### ISSUE THREAD

**Issue by gendalv** [sinkillerj/ProjectE#1538] opened 2017-07-04 17:19 UTC
Crashes when trying to place any block in its inventory.
ProjectE-1.11.2-PE1.0.0B.jar
Tried with clean install forge-1.11.2-13.20.0.2201, 1.11.2-13.20.0.2253 and 1.11.2-13.20.1.2425

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 7/4/17 8:15 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:59)
	at moze_intel.projecte.gameObjs.container.inventory.MercurialEyeInventory.setStackInSlot(MercurialEyeInventory.java:22)
	at moze_intel.projecte.gameObjs.container.MercurialEyeContainer.func_184996_a(MercurialEyeContainer.java:57)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:548)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:598)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:552)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

---- Minecraft Crash Report ----

ps: also the game sometimes just crashes randomly, with "player moved wrongly" - can crash in minutes after game load or after a few hours.
ps2: darkmater pedestal doesn't work

**Comment by williewillus** [comment] 2017-07-04 17:24
logs please

**Comment by pupnewfster** [comment] 2020-02-18 00:35
Closing as I am unable to reproduce in 1.15, and it is likely the mecurial eye rework in 1.12 fixed this if it still was happening then.

**Closed by pupnewfster** 2020-02-18 00:35 UTC
