### ISSUE TITLE
Ring of Arcana in bauble slot needs to be re-equipped after dimension transition

### ISSUE THREAD

**Issue by Stalkstalks** [sinkillerj/ProjectE#1152] opened 2016-01-18 22:26 UTC
I was using a Ring of Arcana as a flight tool. It can be equipped in a bauble ring slot, and works there - however, after going to the nether (or back from the nether) it stopped allowing flight until I opened the bauble interface, pulled it from the slot, and put it back.

**Comment by Robotia** [comment] 2016-01-24 15:08
@Stalkstalks same problem with the SWRG in #1141

**Comment by cookta2012** [comment] 2016-02-29 16:18
This is a Baubles issue, it even occurs in the 1.7.10 version of baubles

**Comment by williewillus** [comment] 2016-03-08 21:39
Can't reproduce

**Comment by pupnewfster** [comment] 2020-02-18 00:19
Closing this as we no longer use baubles (it isn't updated to 1.15), and I don't believe this is an issue anymore with the Curios integration.

**Closed by pupnewfster** 2020-02-18 00:19 UTC
