### ISSUE TITLE
1.8 World Not Loading

### ISSUE THREAD

**Issue by catzs** [sinkillerj/ProjectE#862] opened 2015-07-22 16:21 UTC
In my custom 1.8 modpack, whenever I load up a world with ProjectE installed I get a crash or a freeze(based on ProjectE version). I even tried loading up Minecraft with only forge and ProjectE installed. Got this crash: http://pastebin.com/xrcV9jRc
Maybe it is forge version, but I read the other issues, saw something similar, but saw the fix in the code, updated and still had weird issues. 
What version of forge was 1.8 ProjectE built against?
Thanks

**Comment by GirafiStudios** [comment] 2015-07-22 16:30
Duplicate of #856

**Comment by williewillus** [comment] 2015-07-22 16:37
Not a dupe, the pregenerated json is failing to read.
@MaPePeR ?
getNameForObject now returns Object (but actually a ResourceLocation), wondering if it's safe to just do resourcelocation.toString()
Code in question: https://github.com/sinkillerj/ProjectE/blob/MC18/src/main/java/moze_intel/projecte/emc/pregenerated/NSSJsonTypeAdapter.java#L26
It used to return a string in 1.7

**Comment by MaPePeR** [comment] 2015-07-22 16:51
@williewillus depends. i need the unique-identifier name that i can use to request the item from the registry. (Using `Item.itemRegistry.getObject(itemName);`)

if `resourceLocation.toString()` is that string - should work...

**Comment by williewillus** [comment] 2015-07-22 16:53
ah yeah they changed the key for that map to resourcelocation. Both the read/write methods need to be changed for that, but shouldn't be a hard fix

**Comment by catzs** [comment] 2015-07-22 20:28
So have you fixed and released to solution to #856

**Comment by williewillus** [comment] 2015-07-22 23:51
That is another bug, this one I still need to do.
As MaPePeR said, disable pregenerated emc in mapping.cfg

**Comment by catzs** [comment] 2015-07-23 20:39
OK did so, thnx. And the other bug appears in some loads and not others. So I can load up my world sometimes??

**Comment by williewillus** [comment] 2015-07-23 20:58
The other bug is unpredictable. This one can be resolved by turning off pregenerated emc.

**Comment by GirafiStudios** [comment] 2015-07-23 21:33
I will close this again. Looks like it have been fixed with a recent commit. Good job @williewillus ^^

**Closed** 2015-07-30 21:13 UTC
