### ISSUE TITLE
Attempts to /projecte reloadEMC failed

### ISSUE THREAD

**Issue by lukeimyafada** [sinkillerj/ProjectE#1550] opened 2017-07-27 17:07 UTC
after attempting to set a value for yellorium or uranium (extreme reactors and industrialcraft 2 mod packs)
the value sets, however on attempt to reload the emc by typing the following command
/projecte reloadEMC

i get the following messages
Reloading EMC values, expect lag.
An unknown error occured while attempting to perform this command

will attempt to upload modpack and screenshot of my screen as i am unable to find a log and game output from minecraft launcher shows nothing
[FTB Beyond Custom-1.10.0.zip](https://github.com/sinkillerj/ProjectE/files/1180700/FTB.Beyond.Custom-1.10.0.zip)
![screenshot](https://user-images.githubusercontent.com/5057385/28682857-9fac02fe-733d-11e7-92a8-f8cd486275c0.png)

**Comment by lukeimyafada** [comment] 2017-07-27 17:08
also i dont know if this is relevant but when i close the game down back to main menu, the game will not reload, unless i restart the entire program, and it only does it after setting a new emc value

**Comment by pupnewfster** [comment] 2020-02-18 00:34
Closing as the entire command system in minecraft has been rewritten and I am unable to reproduce in 1.15

**Closed by pupnewfster** 2020-02-18 00:34 UTC
