### ISSUE TITLE
CTD When searching in transmutation table/tablet

### ISSUE THREAD

**Issue by AzarathXorn** [sinkillerj/ProjectE#493] opened 2015-02-15 18:47 UTC
After making the Tome of Alchemical Knowledge and using it, whenever I type a letter into the tablet's search bar, the game crashes to the desktop. Tested with table and tablet, same for both. The crash report can be found [here] (http://puu.sh/fXp8z/f0e0f916c3.txt). I'd love some advice on how to fix this. I didn't see any reports of people having the same issue in my googling, so hopefully this is a quick fix. Thanks!

**Comment by sinkillerj** [comment] 2015-02-16 18:28
Duplicate of a known issue, please test again in the next version as a fix will be applied to it that should fix this, I have been unable to reproduce it myself but I believe I know whats going on.

**Closed by sinkillerj** 2015-02-16 18:28 UTC
