### ISSUE TITLE
[Request] Pedestals

### ISSUE THREAD

**Issue by drifter397** [sinkillerj/ProjectE#465] opened 2015-02-06 03:49 UTC
IIRC, there was a dark matter and red matter pedestal back in EE2. Maybe you could relive the moment and bring it to life? I am a huge fan and love how you brought it back. Thank you.

~drifter397

**Comment by sinkillerj** [comment] 2015-02-06 05:47
Duplicate of #449

**Closed by sinkillerj** 2015-02-06 05:47 UTC
