### ISSUE TITLE
Progressive Automation

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#367] opened 2015-01-02 02:44 UTC
Currently with Progressive automation installed alongside ProjectE, Wood and stone tools have insane EMC values due to seeing a crafting recipe for special wood swords from progressive automation, using Nether stars:

http://i.imgur.com/PTVlyHv.png
http://i.imgur.com/fz3Lit0.png
http://i.imgur.com/WnVGeDN.png

As with my last issue, not sure who's side this falls on, so I'l post on both Githubs.

Using Mod versions:
PROJECTE-ALPHA 0.2D-DEV11
PROGRESSIVEAUTOMATION-1.7.10-1.5.6

**Comment by sinkillerj** [comment] 2015-01-02 08:02
Closing as this is resolved in recent commits and is a duplicate issue. The fixes will be in dev13.

**Closed by sinkillerj** 2015-01-02 08:02 UTC

**Comment by IAA-ShRaPNeL** [comment] 2015-01-02 12:14
Ahh. Awesome. Didn't see that it was fixed.

**Comment by MaPePeR** [comment] 2015-01-02 12:23
Duplicate of #356, fixed by 981299e6d4d204ecb035513393efb2d114372c7f.
Should also be fixed by ed4d93abbe83e1a38ad6a5ce40cfa432f5014f0f / PR #363, which makes the 981299e6d4d204ecb035513393efb2d114372c7f fix unnecessary.

**Comment by IAA-ShRaPNeL** [comment] 2015-01-02 23:23
Lovely. Thanks for the quick reply.
