### ISSUE TITLE
Running projecte_setEMC command wipes the transmutation table

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#657] opened 2015-04-19 10:28 UTC
I ran the projecte_setEMC command with the latest version of ProjectE  (1.4.4), and noticed that it said the value was set right away.  So, I opened up my transmutation tablet to put the new item in, and noticed that all learned items had been wiped from the transmutation tablet.  I was also unable to add/teach anything to it.  I looked at the console and saw that the remapping thread was still running, and then waited.  After it was done, the learned items were still gone, and they were still gone even after a relog.

I then I went into a test world and found that simply opening the transmutation GUI while the remapping operation is running will trigger the wipe.  If you do not open the transmutation GUI until after the remapping has finished, then the problem does not occur.

**Comment by Parker8283** [comment] 2015-04-19 11:01
God. Dang. It.

Ok, so I can't reproduce this with just ProjectE, but if I'm understanding this correctly, it's because all the mods installed make it so remapping takes longer. Best solution might be to send the chat message in the thread at the end.

Also, possibly, make Transmutation thread safe.

**Comment by MaPePeR** [comment] 2015-04-19 11:02
Best solution: don't change emc values on the fly ;)

**Comment by Parker8283** [comment] 2015-04-19 11:05
...
...
...
I hope that's a joke :P

**Comment by Parker8283** [comment] 2015-04-19 12:52
#658 Should cause less confusion.

**Comment by williewillus** [comment] 2015-04-19 13:47
Perhaps also disallow transmutation gui's from being opened while the EMC values are in unusable state?

**Comment by zauberparacelsus** [comment] 2015-04-19 14:12
@williewillus Yeah, that's probably the solution I was thinking would be chosen.

@Parker8283 Yeah, I have a ton of mods, enough that NEI has over 600 pages worth of stuff.  Most of those are forge microblocks, though.

**Comment by Parker8283** [comment] 2015-04-19 23:41
Not just the transmutation. Anything that has anything to do with EMC values has to be blocked. Which probably includes any gui that shows the player's inventory because of tooltips. My PR will just cause less confusion for now, while we work on a good solution.

**Comment by zauberparacelsus** [comment] 2015-04-19 23:42
@Parker8283 While the remapping is being calculated, EMC values are omitted from all tooltips.  So, it looks like it's already blocking EMC values in some areas.

**Comment by Zaflis** [comment] 2015-04-22 06:14
This seem to happen in multiplayer, possible when you are using transmutation table while another player uses /projectE_setEMC . Both of us have now lost alot of the saved items from table.

**Comment by MSandro** [comment] 2015-04-22 06:24
I've noticed this problem on my server. When I tried to remove a value, I've lost a few things from the table/tablet.

**Comment by MaPePeR** [comment] 2015-04-22 06:56
Personally i think that this is not a problem that we should solve in every single file of our code.

If we change the messages to be more specific like: 

> EMC Mapping started. DO NOT USE YOUR TABLETS
> EMC Mapping finished.

its a very avoidable problem. 
For me setting EMC values is something you do once - before you even publish or play the pack - and not when a server is running and people are playing on it.

**Comment by Time6628** [comment] 2015-04-29 00:50
When I do this all I do is relog and it's back.

**Comment by Zaflis** [comment] 2015-04-29 00:58
Don't count on it, they didn't come back when i relogged at the time.

**Comment by MaPePeR** [comment] 2015-05-04 09:15
Maybe a better fix would be to not clear the old values until the new values are calculated. 
Or is that already the case?

**Comment by williewillus** [comment] 2015-05-04 12:27
No, they're cleared before remapping is done (see ThreadReloadEMC)

**Comment by RoqueDeicide** [comment] 2015-05-05 06:11
I would like to mention that not only registering new EMC values may wipe your transmutation tablets: any errors that happen during that process will clear all custom EMC you've set previously. For instance, I tried setting an EMC value for a tartarite tool rod from ExtraTiC and that caused the process to fail and made all items with custom EMC that I gave to them loose that value. Then, when I opened the transmutation table, all of those items were gone.

My suggestion for solving this issue is to not remove an item that doesn't have an EMC value from the table or any energy condenser slots, prevent any normal functions for them (transmutation table will not accept/produce those items, condenser won't make them either) and have a special command that can be used by admins to clear tables/condensers from invalid items in case they actually want the items to have their custom EMC values cleared.

**Comment by Zaflis** [comment] 2015-05-05 06:44
Better solution would be for server to tell clients to close all opened tables, and not let it open until emc values are done recalculating. Even better, not start recalculation until those tables are closed first.

But easier is to tell all world admins how the emc works. These values aren't normally changed while playing, but when making a modpack.

**Comment by RoqueDeicide** [comment] 2015-05-05 08:39
**Zaflis**, that only works, if there were no errors during the recalculation or the system rolls back to old EMC database in case of the error.

Telling everyone to close and not open the tables is not foolproof and not randomstuffproof.

I'm playing in singleplayer in a private modpack that is constantly evolving and I have to introduce custom EMC values almost every session, and I don't quite trust myself enough to exercise enough restraint to not open anything before recalculation is done without any errors. Also rolling back to the previous database is quite tricky and requires deleting the faulty EMC from the file and setting the value for something else that will work.

**Comment by Zaflis** [comment] 2015-05-05 08:57
I meant not telling, but forcing. UI simply closes itself by a network packet that tells it to. Right clicking a tablet would also do nothing until given permission to.

**Comment by MaPePeR** [comment] 2015-06-30 20:01
@sinkillerj fixed by removing the thread, i think.

**Comment by sinkillerj** [comment] 2015-06-30 20:10
Yea, if this happens again it will be a completely different cause and will require completely new logs, closing.

**Closed by sinkillerj** 2015-06-30 20:10 UTC
