### ISSUE TITLE
[1.12.2] World Corrupts with philosophers stone

### ISSUE THREAD

**Issue by MrEyeballs29** [sinkillerj/ProjectE#1849] opened 2019-03-23 22:53 UTC
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version: ProjectE-1.12.2-PE1.4.0

Exact Forge version: forge-1.12.2-14.23.5.2823

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://hastebin.com/ocaroxojuz.rb

Steps to reproduce:

1. I pulled a philosopher's stone with using creative mode.

2. then this happen.

What I expected to happen: Nothing.

What happened instead: It crashed and world became corrupted.

**Comment by pupnewfster** [comment] 2019-03-24 03:47
Duplicate of #1821 . Fixed in dev, for now just install JEI

**Closed** 2019-03-31 02:06 UTC
