### ISSUE TITLE
Crashes when I see in JEI page with PE blocks - after ~1 min 1.9.4

### ISSUE THREAD

**Issue by ircmaan** [sinkillerj/ProjectE#1249] opened 2016-06-06 21:10 UTC
In the beginning ALL of crash reports there is lines:
-------
java.lang.NullPointerException: Rendering screen
	at moze_intel.projecte.gameObjs.items.rings.MindStone.getStoredXP(MindStone.java:155)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.func_77624_a(MindStone.java:85)
-------
[crash-2016-06-06_09.55.15-client.txt](https://github.com/sinkillerj/ProjectE/files/301342/crash-2016-06-06_09.55.15-client.txt)

**Comment by MaPePeR** [comment] 2016-06-06 21:12
Duplicate of #1239. Fixed in next release.

**Closed** 2016-06-06 21:58 UTC
