### ISSUE TITLE
0 in Transmutation Table  (Minecraft 1.10.2)

### ISSUE THREAD

**Issue by GIGAAj1** [sinkillerj/ProjectE#1373] opened 2016-10-14 23:36 UTC
If you click Shift in the Transmutation Table on the item you want, the item gets a zero but this only happens at a certain point in the table.
![2016-10-15_01 35 07](https://cloud.githubusercontent.com/assets/2996236/19405447/ce260e10-9277-11e6-87b4-fd8ebb82f90b.png)

**Comment by GIGAAj1** [comment] 2016-10-15 01:01
Wenn man Shift klickt ist der Punkt unten von der Mitte.

**Comment by Iyasenu** [comment] 2016-10-15 15:40
I've also run into this issue.
A few possible spots I've had this happen to me are in the bottom slot of the inner ring, and the bottom center slot of the outer ring.

Having the tablet "unlearn" the item and learning it again is a temp workaround, but you can still "zero" items out in the future.
And having the 0'd out item in a different slot, like if you change pages or something, lets it be clickable if you don't currently have a copy to do the unlearn/relearn thing.

A weird happening, is that when this happens, it seems like the tablet uses up the EMC for 1 of the afflicted items, but doesn't actually give you anything.

**Comment by zzApotheosis** [comment] 2016-10-17 08:07
I believe this is a duplicate of #1331.

**Comment by williewillus** [comment] 2016-10-17 12:21
Hm and it only happens on these two slots no other?

**Comment by GIGAAj1** [comment] 2016-10-20 13:38
It happens in all left slots only in the two mentioned most frequently.

I think it is because of the fact that the table has too little EMC and therefore shiftclick in minus EMC would go, which he can not and therefore because a 0 stands.
A math error from the table.

**Comment by HellishINC** [comment] 2016-11-01 03:27
> I think it is because of the fact that the table has too little EMC and therefore shiftclick in minus EMC would go, which he can not and therefore because a 0 stands.

I can say that this is not the case. There are times when I have well over 20k EMC and I still see this bug. I have ONLY seen it occur with redstone/coal/charcoal.

**Comment by RubikMonat** [comment] 2016-11-13 03:08
Getting this fairly regularly. Glowstone, Charcoal, Coal is what I have seen so far. Stays as the red 0 until a restart. Even with enough EMC for a stack it still happens, but it does seem to happen more often with EMC in the 20k range.

**Closed** 2016-11-13 21:29 UTC
