### ISSUE TITLE
Transmutation Tablet learns itself?

### ISSUE THREAD

**Issue by tehbasshunter** [sinkillerj/ProjectE#1451] opened 2016-12-21 17:36 UTC
Title is self explanatory.

Experienced this strange bug/occurrence during a livestream last night.

[Twitch Clip](https://clips.twitch.tv/tehbasshunter/WonderfulPorcupineFUNgineer)

**Comment by Tencao** [comment] 2016-12-21 18:59
Intended as far as I know. It's a useful way to duplicate one for a friend or just simply a spare one.  I don't think being able to destroy itself is intended though, usually there's some kind of protection from you picking up the transmutable while it's open, unless that's broken again

**Comment by sinkillerj** [comment] 2016-12-22 05:33
This is indeed intended behavior. As for the GUI not closing when broken it is a known and minor bug, trying to fix it causes more trouble than it causes on its own.

**Closed by sinkillerj** 2016-12-22 05:33 UTC

**Comment by Tencao** [comment] 2016-12-22 09:35
As a suggestion to prevent accidental deletion, maybe filter the transmutable tablet from shift clicking, so if players wish to destroy their tablet for whatever reason, they still can
