### ISSUE TITLE
Issue w/ Latest Build

### ISSUE THREAD

**Issue by O13SC3N3** [sinkillerj/ProjectE#550] opened 2015-03-17 08:05 UTC
Forge 1307 Java 1,8 MC 1.7.10

following error occurs after spawn generation.

[02:02:30] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[02:02:30] [Server thread/ERROR] [FML]: Caught exception from ProjectE
java.lang.NullPointerException
	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:45) ~[EMCMapper.class:?]
	at moze_intel.projecte.PECore.serverStarting(PECore.java:127) ~[PECore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.2.1307-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[forge-1.7.10-10.13.2.1307-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[forge-1.7.10-10.13.2.1307-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[02:02:30] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
java.lang.NullPointerException
	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:45) ~[EMCMapper.class:?]
	at moze_intel.projecte.PECore.serverStarting(PECore.java:127) ~[PECore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.2.1307-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by MaPePeR** [comment] 2015-03-17 15:22
is that issue new? did you not have that problem with the 1.4.0 version?

**Comment by O13SC3N3** [comment] 2015-03-17 18:21
Not on 1.4 no just .41

**Comment by MaPePeR** [comment] 2015-03-18 17:10
Is this any special public pack?

**Comment by O13SC3N3** [comment] 2015-03-18 19:10
Well kind of a hybrid of infinity. 1.40 does fine its 1.41 uli get the crash

**Comment by jackalodian** [comment] 2015-03-19 20:50
I get this problem too. I also get it on 1.4.0, though.

**Comment by MaPePeR** [comment] 2015-03-19 21:15
If that same NPE was already a problem in 1.4.0 thats actually kind of good news. Because i could not explain to myself how the changes of 1.4.1 add this.

I think it might be caused by [`GraphMapper.setValue`](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/emc/GraphMapper.java#L115) not preventing `null`-Entrys, which then causes the [`normstack.damage`](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/emc/EMCMapper.java#L45) to NPE.

**Comment by jackalodian** [comment] 2015-03-19 21:21
Well... I removed Mariculture and it was fine... I had Mariculture in my modpack for some reason... It is not in Infinity by default, so if O13SC3N3 added it... that is probably the problem.

**Comment by MaPePeR** [comment] 2015-03-19 21:48
Thank you very much for investigating this. This will be very helpful!

**Comment by O13SC3N3** [comment] 2015-03-19 21:59
Nope do t have that mod, I'll post a mod list when I get off work.

**Comment by jackalodian** [comment] 2015-03-19 22:15
No problem MaPePeR, and thanks O13SC3N3, I will Investigate further once I can.

**Comment by O13SC3N3** [comment] 2015-03-24 02:36
[23/3/2015 19:24:06 PM] [Server thread/ERROR] [FML]: Caught exception from Sanguimancy
[23/3/2015 19:24:06 PM] [Server thread/ERROR] [FML]: Caught exception from ProjectE
[23/3/2015 19:24:06 PM] java.lang.NullPointerException
[23/3/2015 19:24:06 PM] 	at com.mcjty.rftools.items.dimlets.KnownDimletConfiguration.setDimletKey(KnownDimletConfiguration.java:1052) ~[KnownDimletConfiguration.class:?]
[23/3/2015 19:24:06 PM] 	at com.mcjty.rftools.crafting.KnownDimletShapedRecipe.func_77571_b(KnownDimletShapedRecipe.java:21) ~[KnownDimletShapedRecipe.class:?]
[23/3/2015 19:24:06 PM] 	at moze_intel.projecte.emc.mappers.CraftingMapper.addMappings(CraftingMapper.java:29) ~[CraftingMapper.class:?]
[23/3/2015 19:24:06 PM] 	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:31) ~[EMCMapper.class:?]
[23/3/2015 19:24:06 PM] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
[23/3/2015 19:24:06 PM] java.lang.NullPointerException
[23/3/2015 19:24:06 PM] 	at com.mcjty.rftools.items.dimlets.KnownDimletConfiguration.setDimletKey(KnownDimletConfiguration.java:1052) ~[KnownDimletConfiguration.class:?]
[23/3/2015 19:24:06 PM] 	at com.mcjty.rftools.crafting.KnownDimletShapedRecipe.func_77571_b(KnownDimletShapedRecipe.java:21) ~[KnownDimletShapedRecipe.class:?]

So by trial and error I found the issues for me was any forge after 1291, any rfftools beyond 2.64. any sanguinmancy (not sure how does emc any items in it) above PRE-21

currently ProjectE 1.41 is working, just not sure if the mapper is working 100% seems like it misses a lot.

**Comment by sinkillerj** [comment] 2015-03-28 12:25
Fixed in latest build, closing.

**Closed by sinkillerj** 2015-03-28 12:25 UTC
