### ISSUE TITLE
Transmutation Table increased EMC limit (Enhancement Suggestion)

### ISSUE THREAD

**Issue by thefnitalian** [sinkillerj/ProjectE#1637] opened 2018-01-09 05:11 UTC
I would like to see the transmutation table’s EMC be saved as a BigInteger value so that we dont hit a cap. (Enhancement Suggestion)

**Comment by sinkillerj** [comment] 2018-01-09 17:50
Duplicate of  #1636 and unlikely to be implemented at this time.

**Closed by sinkillerj** 2018-01-09 17:50 UTC
