### ISSUE TITLE
Interdiction torch repels Tinker's Construct shuriken

### ISSUE THREAD

**Issue by chimericdream** [sinkillerj/ProjectE#1643] opened 2018-02-07 04:54 UTC
ProjectE version: [1.12-PE1.2.0](https://minecraft.curseforge.com/projects/projecte/files/2518569) 
Forge version: 1.12.2-14.23.1.2604
Link to crash log: n/a

Steps to reproduce:
1. Craft a shuriken from TiCon (I'm using v1.12.2-2.9.0.55, for reference)
1. Place an interdiction torch
1. Try to throw shuriken near (or directly at, for extra fun) the torch
1. Watch the projectiles go haywire

What I expected to happen:
I didn't expect shuriken to be affected by the interdiction torch.

What happened instead:
They were.

**Comment by chimericdream** [comment] 2018-02-07 05:34
I just discovered that the same issue happens with mana pulses from Botania's mana spreaders. Since it is likely the same root cause, I'm just adding to this issue rather than create a second.

**Comment by sinkillerj** [comment] 2018-02-07 14:22
It sounds like your config is set to B:interdictionMode=false instead of true.

**Comment by chimericdream** [comment] 2018-02-07 14:40
I didn't think to check that, but it is indeed set to true on both my client and server.

**Comment by sinkillerj** [comment] 2018-02-08 01:01
Hmm, true would be the correct setting. Is it also repelling mobs such as pigs? If so the config may be getting ignored and ill have to look into it.

**Comment by williewillus** [comment] 2018-02-08 04:30
Interdiction mode is just for mobs/living things.

It is intended behaviour for the torch to reflect all other projectile type entities.

Botania has an IMC to disable burst affecting it so if that's not working it's a separate issue.

**Comment by chimericdream** [comment] 2018-02-08 04:31
I just did a quick test, and neither a pig nor a sheep got repelled. A creeper did, though.

**Comment by chimericdream** [comment] 2018-02-08 05:35
@williewillus I'm not sure what you mean. I didn't see anything in either the Botania or ProjectE config files that looked like it would specifically disable the interdiction torch affecting the spreader. But if that's a separate issue, I can close this one and open a new one. Just want to clarify what you meant first in case it's something I missed.

**Comment by sinkillerj** [comment] 2018-02-10 01:25
Willie is correct, forgot that it would be considered a projectile. Closing due to intended behaviour.

**Closed by sinkillerj** 2018-02-10 01:25 UTC
