### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Yoreni** [sinkillerj/ProjectE#1782] opened 2018-12-08 09:59 UTC
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.3.2h

Exact Forge version: 14.23.5.2776

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://hastebin.com/husepeqoya.rb

Steps to reproduce:

1.click play on the launcher
2.wait to phase 4/7
3.game crashes

What I expected to happen: the game loaded with projectE installed

What happened instead: the game crashed when it just started phase 4/7 of loading

**Comment by pupnewfster** [comment] 2019-01-29 01:19
Duplicate of #1781, and is already fixed in dev

**Closed** 2019-01-29 16:13 UTC
