### ISSUE TITLE
Transmutation table pulling out wrong items

### ISSUE THREAD

**Issue by rhyssean** [sinkillerj/ProjectE#491] opened 2015-02-14 18:52 UTC
So i'm trying to get iron, so I search it up in NEI. And when i try to get the iron ingot from the table (has 200 000 EMC in it), it takes a diamond horse armor. So I can't get the iron, whether i'm shift clicking it or just taking one, it gives me the thing that's highest emc in the table

**Comment by MaPePeR** [comment] 2015-02-14 18:53
Duplicate of #413 which is fixed in the current version.

**Closed** 2015-02-14 20:45 UTC
