### ISSUE TITLE
Slots un-aligned. 

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#452] opened 2015-02-03 19:54 UTC
For a few items, the Slots in the Tablet show different items than what they actually are. For example, it will show me a Solid oak door, but the items you receive when attempting to take the door out are actually Oak Logs. 

Also, some slots that show no item actually do contain an item. Searching Obsidian and clicking an empty space will give me Chiseled Obsidian from Chisel. Attempting to get Chiseled obsidian from where the GUI shows it gives me Vanilla Obsidian. Trying to grab Vanilla obsidian from where it shows gives me Obsidian Pressure plates.

The items in the tablet GUI are pretty much shifted around. 

I should also add that i'm using the Resonant Rise 3 Excessive modpack.

**Comment by sinkillerj** [comment] 2015-02-03 21:33
This is a duplicate of a known issue, it is resolved in the latest commit and will be available in the next build.

**Closed by sinkillerj** 2015-02-03 21:33 UTC

**Comment by IAA-ShRaPNeL** [comment] 2015-02-03 23:54
Awesome.
