### ISSUE TITLE
Alchemical bag + Black Hole Band = bag data clearing

### ISSUE THREAD

**Issue by Azanorashit** [sinkillerj/ProjectE#692] opened 2015-05-05 03:04 UTC
So I ran into this extremely annoying problem where grinding some skeleton spawner with a scythe and having the items auto fill into an alchemical bag is causing the bags data to reset, and it's happened twice. I'm not sure exactly whats causing it to happen, but I figure if I brought the log of everything that games done then someone would see the cause of the problem. Now, I omitted a huge portion of it because it went well over pastebins file size limit, but this is what I assume to be the important stuff, the stuff that I think was going on while I was actively playing. 

As soon as I noticed the bags cleared again I hit esc to pause the game the force shut down the game with the task manager and got the game log. If I really need to, I can try to recreate it again and use a webm as a video record.

http://pastebin.com/rqJYJVmz

**Comment by Azanorashit** [comment] 2015-05-05 05:19
I went to try and replicate it again, and these are the last lines to happen before the bags reformat themselves.

[00:16:23] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.gui.GUIAlchChest
[00:16:23] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.container.AlchBagContainer
[00:16:24] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu

I don't what what to make of this cause i'm not a coder, but this is as much as I can narrow it down.

**Comment by MaPePeR** [comment] 2015-05-05 18:33
I don't see anything in this log.

The only thing i can think of would be the band picking up an item at the same time the bag is saved.

**Comment by sinkillerj** [comment] 2015-05-05 19:06
Duplicate of a known issue.

**Closed by sinkillerj** 2015-05-05 19:06 UTC
