### ISSUE TITLE
Using NEI to search items in the tablet

### ISSUE THREAD

**Issue by misterfixit** [sinkillerj/ProjectE#385] opened 2015-01-10 23:14 UTC
http://puu.sh/elyLb/863e6bfbe2.txt

I crash to desktop when searching for items in the transmutation table and tablet

**Comment by misterfixit** [comment] 2015-01-10 23:16
The version I am using is dev11 btw

**Comment by misterfixit** [comment] 2015-01-11 00:25
tested in dev13 as well still exists

**Comment by Kolatra** [comment] 2015-01-11 01:09
Version of NEI and CCC?

**Comment by misterfixit** [comment] 2015-01-11 01:12
NEI-1.7.10-1.0.3.74-Universal
CCC-1.7.10-1.0.4.29-Universal

**Comment by Kolatra** [comment] 2015-01-11 21:16
I can't reproduce this. Haven't had this issue for a few versions now.

**Comment by misterfixit** [comment] 2015-01-11 23:02
im using forge version 10.13.2.1277 if that helps

**Comment by misterfixit** [comment] 2015-01-17 01:37
Well this issue is present in the RR3 pack. I'm one of the pack devs, so continuing to troubleshoot could it be one of the nei addon mods?

**Comment by Kolatra** [comment] 2015-01-17 02:06
Try updating to dev13 and let me know what happens.

**Comment by misterfixit** [comment] 2015-01-17 02:08
It still exists in dev13

**Comment by MaPePeR** [comment] 2015-01-17 09:58
I think this is the "unlocalized name = null" bug. This *might*  be fixed by my NEI - search pull request. #377

**Closed** 2015-03-12 18:22 UTC
