### ISSUE TITLE
QED screws with item selection in transmutation tablet

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#1070] opened 2015-10-27 14:46 UTC
The QED item from the Extra Utilities mod is rather unique in that its name can change.  The name is always written as "QED (Quantum...)" where the Quantum is followed by a random word starting with E and then a random word starting with D.  For example, "QED (Quantum Enrichment Device)" or "QED (Quantum Ender Diviner)".

This seems to mess up the transmutation tablet.  Any time I type "Ender" into the search and then click on one item, I'll get a different item (usually from the opposite side of the table).  Dropping it into the flames on the GUI to turn it back into EMC will usually (but not always) fix this problem.

**Comment by MaPePeR** [comment] 2015-10-27 16:03
Update ProjectE

**Comment by zauberparacelsus** [comment] 2015-10-27 16:08
From as far as I can tell, the latest build is for Minecraft 1.8.  Resonant Rise is currently on 1.7.10

**Comment by williewillus** [comment] 2015-10-27 16:13
we have parallel branches, the latest version of PE for 1.7 is 1.9.3H.
Resonant Rise is for some reason still using absurdly ancient versions of ProjectE, last time I checked.

**Comment by zauberparacelsus** [comment] 2015-10-27 16:14
Okay, I'll give 1.9.3h a try

**Comment by zauberparacelsus** [comment] 2015-10-27 16:40
Problem is fixed, though now when I type in "Ender" it seems to also list all recorded items from the Ender IO mod.

**Comment by MaPePeR** [comment] 2015-10-27 17:06
Thats not a bug, its a feature

**Comment by iHeartZigg** [comment] 2015-10-27 17:12
I think it would be better to search for mods only if it starts with "@" like NEI used to do.

**Comment by zauberparacelsus** [comment] 2015-10-27 17:18
@MaPePeR I realize you mean that seriously, though 90% of the time I hear that expression used in a sarcastic context.

@iHeartZigg I agree

**Comment by MaPePeR** [comment] 2015-10-27 17:30
@iHeartZigg The Transmutation Table will give you the EXACT same results NEI does... Which is why i consider this a feature and not a bug.

**Comment by zauberparacelsus** [comment] 2015-10-27 19:01
@MaPePeR by the way, I noticed that EMC recalculation is MUCH faster now, and completes within a few seconds.  Is that just from optimization, or is it threaded now?

**Comment by MaPePeR** [comment] 2015-10-27 19:17
@zauberparacelsus its not threaded. i *think* i fixed a bug some time ago that could make it slow - but i don't know if that was merged/released or is still in a PR.

The amount of time it takes highly depends on the mods and recipes that are present, though. - And pregenerated EMC is also an option to make it load the values instantly.

**Closed** 2015-10-27 23:45 UTC
