### ISSUE TITLE
[1.15.2] EMC values don't work and are not visible

### ISSUE THREAD

**Issue by jiru6552** [sinkillerj/ProjectE#2058] opened 2020-09-17 17:02 UTC
Exact ProjectE version: ProjectE-1.15.2-PE1.0.4

Exact Forge version: Forge-31.2.41

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A
Steps to reproduce:

1. Have ProjectE PE1.0.4.jar, Futurepack 20.1.0.jar, Thermal Expansion 0.2.3b, Cofh Core 0.6.2b, and Thermal Foundation 0.2.2b downloaded.
2. Launch game.
3. Create new world.
4. Check for EMC values.
5. Check to see if blocks/items that accept EMC accept Vanilla Minecraft blocks. Ex: placing a stone block in the exchange tablet.

What I expected to happen: EMC to be visible and usable.

What happened instead: EMC was not visible or usable.

Note: Removing Futurepack or Thermal Expansion will cause EMC values to work again, but not with both downloaded at once.

**Comment by jiru6552** [comment] 2020-09-28 02:49
[Link](https://github.com/mcenderdragon/Futurepack-API/issues/699) to Futurepack issue

**Comment by pupnewfster** [comment] 2020-09-28 02:53
Could you please provide your latest log, my guess is that it is printing an exception for one of the other mods having a recipe made out of invalid items and causing the calculations to crash.

**Comment by jiru6552** [comment] 2020-09-28 03:08
[latest.log](https://github.com/sinkillerj/ProjectE/files/5289730/latest.log)
Just a note, for this log I did update to Thermal Expansion 0.3.0b, Cofh Core 0.7.0b, and Thermal Foundation 0.3.0b. The problem persists though.

**Comment by pupnewfster** [comment] 2020-09-28 11:37
My best guess is that thermal expansion is causing the reload listeners to not fire:
```
[23:02:22] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at cofh.thermal.expansion.util.managers.machine.BottlerRecipeManager.refresh(BottlerRecipeManager.java:190) ~[?:0.3.0b]
	at cofh.thermal.core.common.ThermalRecipeManagers.refreshServer(ThermalRecipeManagers.java:48) ~[?:0.3.0b]
	at cofh.thermal.core.ThermalCore$1.apply(ThermalCore.java:237) ~[?:0.3.0b]
	at cofh.thermal.core.ThermalCore$1.func_212853_a_(ThermalCore.java:226) ~[?:0.3.0b]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$3643/640995328.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$3961/42598273.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) ~[?:?]
	... 5 more
```

**Comment by mcenderdragon** [comment] 2020-09-28 15:31
```
[23:02:22] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at cofh.thermal.expansion.util.managers.machine.BottlerRecipeManager.refresh(BottlerRecipeManager.java:190) ~[?:0.3.0b]
	at cofh.thermal.core.common.ThermalRecipeManagers.refreshServer(ThermalRecipeManagers.java:48) ~[?:0.3.0b]
	at cofh.thermal.core.ThermalCore$1.apply(ThermalCore.java:237) ~[?:0.3.0b]
	at cofh.thermal.core.ThermalCore$1.func_212853_a_(ThermalCore.java:226) ~[?:0.3.0b]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$3643/640995328.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$3961/42598273.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) ~[?:?]
	... 5 more
```
This seems like the only important crash here.

**Comment by jiru6552** [comment] 2020-09-28 17:00
I haven't been able to find an way to post an issue on the CoFH/ThermalFoundation github page. I've sent a message on the Team CoFH discord page a bit ago and King Lemming said, "That's almost certainly a futurepack issue. I don't touch EMC or Project E in any way, there is absolutely 0 integration."

**Comment by pupnewfster** [comment] 2020-09-28 17:16
I am going to go ahead and close this for now as I don't think ProjectE has anything to do with this issue, as from what I can tell Thermal Expansion is looking at buckets for all fluids, futurepack adds fluids without buckets and returns null from `Fluid#getFilledBucket` instead of doing what forge does/letting forge return air like it does in its implementation in `ForgeFlowingFluid#getFilledBucket` for if there is no bucket... and then this crashes the reload listeners from firing causing ours to never fire.

**Closed by pupnewfster** 2020-09-28 17:16 UTC

**Comment by mcenderdragon** [comment] 2020-09-28 19:34
um actually I dont touch buckets. The Fluid Properties have a bucket supplier which is null by default, so unless I am adding buckets for all fluids I cant fix this...

**Comment by pupnewfster** [comment] 2020-09-28 19:42
Ah actually I just assumed that was the case because the [line](https://github.com/KingLemming/1.15/blob/master/ThermalExpansion/src/main/java/cofh/thermal/expansion/util/managers/machine/BottlerRecipeManager.java#L190) that is throwing an exception and forge's implementation [checks](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/fluids/ForgeFlowingFluid.java#L112) if the supplier is null made it most likely in my mind that you were overwriting and specifically returning null for some reason. If that is not the case, my best guess would be that the still fluid is null? No idea, as I said this issue doesn't have anything to do with ProjectE even without ProjectE installed my guess is that future craft + thermal expansion crashes the reload listeners at that line.

**Comment by mcenderdragon** [comment] 2020-09-28 20:47
yeah its weird something is returning null, and I can not reproduce it with futurepack standalone, only both together seem to cause this.
