### ISSUE TITLE
Unexpected ClassCastException 

### ISSUE THREAD

**Issue by accessdenied0** [sinkillerj/ProjectE#745] opened 2015-05-24 13:56 UTC
Dear @sinkillerj,

In first place I apologize if this crash isn't a fault of ProjectE or this issue is already reported, in the second place I want to report an issue with fastcraft 1.21, because with 1.19 it works fine.

I got here the report for you: http://pastebin.com/402cUg7V

respectful, 

access_denied

**Comment by sinkillerj** [comment] 2015-05-24 18:59
I dont THINK this is a issue on our end, the issue is caused by a client side class being cast to something expecting a server class, the thing is in "onEntityJoinWorld" we are checking "!worldObj.isRemote" which effectively means that line should only be called on the server side. My best guess is your version of FastCraft has broken the isRemote check.

**Comment by sinkillerj** [comment] 2015-05-29 00:13
Anyone else experiencing this with or without FastCraft?

**Comment by Tencao** [comment] 2015-06-01 12:28
I use FastCraft in my pack, and from experience, I have yet to see this issue when a FastCraft client connects to a non-FastCraft server. I'm not sure if that's any help

**Comment by abalabahaha** [comment] 2015-06-06 16:39
FastCraft client connects to non-FastCraft server, no issues at all. Is the server FastCraft?

**Comment by Tencao** [comment] 2015-06-06 18:45
The server isn't fastcraft no, only the clients

**Comment by sinkillerj** [comment] 2015-06-30 20:14
As no further info has been provided, and this should not be the fault of ProjectE, I am closing the issue, should further evidence be provided that shows a potential issues with ProjectE I will be happy to reopen it.

**Closed by sinkillerj** 2015-06-30 20:14 UTC
Labels: needs-info
