### ISSUE TITLE
Make mapping NBT-aware

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1577] opened 2017-08-21 17:25 UTC
cc @MaPePeR 
Opening a ticket for this myself because this will be needed very soon.
In 1.13, Mojang is planning to remove meta from ItemStacks entirely. Literally everything will be done through NBT tags, including "damage" values.
PE needs to at least plan for how it's going to go or else literally the whole mapping system will be broken.

**Comment by sinkillerj** [comment] 2017-08-21 23:48
Oh joy...

**Comment by williewillus** [comment] 2017-08-22 00:31
There's an old PR open for it but I'm skeptical of how it hasn't been tested. That could be a starting point but a major rework will still be needed .

**Comment by sinkillerj** [comment] 2017-08-22 02:03
We may have to just wait and see what comes with 1.13. If there is a standardized tag structure that replaces damage it may not be too bad, but my fear is its going to be like it is now, every modder using their own tag names and values.

We could try to crowdsource a tag list which would be downloaded the first time a world was loaded, or when updated via command. But the chances of getting a dedicated community for that is slim.

**Comment by artman41** [comment] 2017-08-22 14:09
This may seem dumb but can you not just add the nbt to the table locally upon adding an item and then when the user is done with the table, send the nbt data to the server, and have the server contain that all in a json, with the mod + possible nbt datas?

**Comment by sinkillerj** [comment] 2017-08-22 14:45
The problem is determining what NBT values should count as a new item, and which should not. For example with a battery you would not want to count the charge level or you could end up with 500 dupes in your knowlodge.

**Comment by MaPePeR** [comment] 2017-08-22 15:45
I hope, that the idea is to use more of ID instead of ID+NBT.

Anyway: How i think we might be able to solve it:
* When a crafting Operation has a Item with NBT as output store NBT-data inside the `NSSItem`. (+ a NBT-blacklist for each ID, to ignore some NBT-Tags).
* Have a Fake-Item for each crafting-ingredient that uses NBT and create conversions for all Items we have that match the crafting-ingredients NBT-requirements. (This assumes we can read & parse these requirements  - the new recipes allow that, right?)
* EMC values now always require NBT-data. Changing NBT ⇒ Item looses EMC. Maybe be a bit sloppy with comparison to allow empty values to match non-existent keys. (So emptying your bag will make it have EMC again)

We should not need to touch the algorithm itself. Only the `.equals`-Method of the `NSSItem` and another Registry that is very similar to what we already do for metadata-wildcard.

**Comment by williewillus** [comment] 2017-11-27 22:52
this actually is going to be much better than I thought it'd be.

basically, everything that used to use meta for "variants" (dyes, wool itemblocks, etc.) is going to be split into its own item e.g. `red_wool`, `purple_dye`, and the damage for tools is moving to NBT.

so basically nothing should change; we should even be able to remove meta-stuff from NSSItem. the JSONs are just gonna get quite a bit bigger :P

**Comment by asiekierka** [comment] 2018-07-02 06:00
That is a good point!

**Comment by pupnewfster** [comment] 2019-02-27 00:35
I recommend pinning this issue, and closing the other issues having to do with EMC per NBT variants. Given I often see people complaining about the fact that things like Mekanism machines, or buckets, etc don't have the correct EMC values, and it would help keep more issues of that type from being made.

The open issues that have to do with this that I believe can be closed:
#962 
#1531 
#1710 
#1731 

#1673 also sort of falls in this list, though it is recommending just automatically disabling EMC for items that have NBT. (Not really ideal for items that store energy in NBT and don't actually have different "items" based on the NBT)

**Comment by williewillus** [comment] 2019-02-27 04:50
this is not likely to happen anymore, really

I'm averse to major changes to 1.12 as its stable and starts winding down.
And in 1.13 anything worth being unique should be flattened to its own item.
I'll leave this up for a bit more but don't expect it happening.

**Comment by DemonfangArun** [comment] 2019-02-27 05:09
You realize that even VANILLA items are going to be moving to nbt data, correct? There is no getting around this. I don't mean to be rude, but if you refuse to support nbt, projectE is going to suffer an agonizing and quick death in regards to 1.13, and will be replaced.

**Comment by williewillus** [comment] 2019-02-27 05:21
your assessment is completely incorrect. vanilla is moving to flattened item instances, and and nbt is being pushed out further as a "last resort only" measure. nothing in vanilla supports nbt natively (tags, recipes, advancements, ...)

throwing out FUD like "suffer an agonizing and quick death" when you don't know what you're taling about isn't helping the discussion.

**Comment by pupnewfster** [comment] 2019-02-27 05:30
Ya it makes sense why not to bother supporting NBT, however I still think you should close the linked issues, even more so now if the plan is to not support NBT.

**Comment by DemonfangArun** [comment] 2019-02-27 06:21
Also, something I'd like to touch on that was briefly mentioned elsewhere. Even if mods have their own nbt tagging setup, would it not be possible to just store the entirety of the nbt data in raw form within the mapping files, then read this back when pulling the item out again? Yes, it would make for a bit larger of a mapping file, but the overall slowdown should be negligible.

**Comment by pupnewfster** [comment] 2019-02-27 06:25
The issue is this would cause a vast amount of duplicate data. You know that battery of yours that goes up to 1 million power, that is 1 million different things you potentially can learn. And a bunch of things like that, that use NBT to store the state of things, it is not primarily used for storing item "types". Some modes use it so that they don't have a large effect on the item limit, but in 1.13 that limit is going away.

**Comment by DemonfangArun** [comment] 2019-02-27 06:57
Yes, it would, but it would guarantee universal compatibility with everything. Alternately you could store the data in a delta format, recording only the differences. It would cut down the data size, and still be universally compatible, but take a tad more work. Both ways would also fix issues like machine upgrades and the like which aren't feasible to do with separate items (unless you want jei to be a bajillion pages long).

And I'm well aware of the item limit going away. My 1.12 pack runs on the new system thanks to jeid, making it that much more forward compatible.

**Comment by pupnewfster** [comment] 2020-02-18 00:33
Closing this as ProjectE for 1.14+ has support for handling NBT (and for mods to add custom processors if they want to scale EMC values for specific items, similar to how we scale EMC values for damaged items).

**Closed by pupnewfster** 2020-02-18 00:33 UTC

**Comment by DemonfangArun** [comment] 2020-02-18 01:57
As much as I respect moving forward, I'm also getting rather upset with what equates to "it's fixed in this version of minecraft that you won't be using for a couple years because all the big mods are nowhere near being ready for it". If it's not too much effort it would still be worth porting back to 1.12.

**Comment by pupnewfster** [comment] 2020-02-18 02:10
It would be a pretty big effort as I spent a few weeks last fall working on finishing up willie's work on the port and cleaning up both the API and adding various QoL features such as the NBT mapping. Not to mention the majority of free time I do have between working on assignments for the various courses I am taking, is spent on continuing to port/rewrite the internals of Mekanism. I do not have the time or energy to try and backport features to 1.12. (I don't even have time to backport the further improvements/fixes I made to ProjectE in 1.15 to the 1.14 branch even though those two branches are a lot closer in functionality/would be "relatively" easy to do.)

**Comment by asiekierka** [comment] 2020-02-18 07:29
"it's fixed in this version of minecraft that you won't be using for a couple years because all the big mods are nowhere near being ready for it" has *always* been the case. I still remember the community upset when Tinker's Construct decided to become exclusive to 1.5.x+ when RedPower 2 was stuck on 1.4.7.

Unfortunately, modders have limited time, and as the community upgrades *every* time, backporting feels like a futile endeavour to many.

**Comment by DemonfangArun** [comment] 2020-02-18 07:58
Ah yes, redpower, I still miss some aspects of it, but life moves on. The big thing that's different this time is the cycle time. 1.12 has had a really long cycle due to forge getting a major rewrite (anyone remember rigusumis modloader? yeah 1.12 forge still had coffee from that floating around, yikes). Mod devs have had to do a lot of rewriting for this on top of all the normal update delay, which has resulted in many big mods still not having even so much as a dev version out yet (ae2 and jeid are two off the top of my head). As much as I and a good chunk of those who play modded MC would love to move forward, we can't. And that's not even mentioning the problems with vanilla Minecraft 1.15 (try putting 20-30 cows in a pen on a 1.15 server and see how your home network likes it, pings to everything, including your router, will go through the roof).
