### ISSUE TITLE
Wrong item pulling out of the Transmutation Tablet.

### ISSUE THREAD

**Issue by MrSpencerRecor** [sinkillerj/ProjectE#475] opened 2015-02-08 18:55 UTC
Version: project-e-1.7.10-0.2d-dev14
 While click on an item, such as coal, or an item conduit, or basically anything, It will take the wrong item out. I noticed what it does. it acts as if the items when you narrow down the search, aren't there, but they really are, try pulling out of a blank spot, you'll get something...
http://gyazo.com/411d2b0d3873fd28198a84bf0c631428
http://gyazo.com/f93bdff695294ee2e0bce975dcb46d23 : when i pulled out the item conduit, i got this

**Comment by sinkillerj** [comment] 2015-02-08 19:18
Duplicate of a known and already resolved issue, please update to the latest version.

**Closed by sinkillerj** 2015-02-08 19:18 UTC
