### ISSUE TITLE
[1.10.2] Transmutation Table EMC & Knowledge Incorrectly Reset

### ISSUE THREAD

**Issue by Starwort** [sinkillerj/ProjectE#1414] opened 2016-11-26 22:26 UTC
I have keepInventory on in my world, and when taking minor fall damage (that managed to kill me :\ it was like 1 heart) my entire table was reset. I had loads of EMC in there at the time so this was **really** annoying. PLEASE fix this.

P.S. Not sure how to tag this so... Can anyone help with that? ;)

**Comment by williewillus** [comment] 2016-11-27 00:06
I doubt this is correlated....
Also, which PE version

**Comment by christofferson** [comment] 2016-11-28 21:42
I'm experiencing this same issue in ProjectE version 1.1.0B for MC 1.10.2. After traveling to and returning from the Nether my transmutation table _appears_ to be reset (both knowledge and EMC) but logging out and back in again appears to restore the correct knowledge and stored EMC.

I can provide a full mod list / Curse profile export if needed.

**Comment by shanesova** [comment] 2016-11-28 22:58
I've been having this happen too, traveling to/from the nether, the end, or any rftools dimension. The table has 0 EMC and nothing learned but save and exit then reload the world and everything is back to normal. At first I thought maybe it had something to do with upgrading to 1.1.0B but I have since started a new world and I am still having this problem.

**Comment by shanesova** [comment] 2016-11-28 23:13
Just noticed this may have been fixed already 3f04ab7d4128499dfad805f213455a92a2a0be25

**Comment by williewillus** [comment] 2016-11-28 23:28
Yes that is unrelated. This ticket is about it happening without dimension changes, but it has no details so I suspect it might just be the prior one

**Comment by Yashimata** [comment] 2016-11-30 19:22
Pretty easy to replicate (at least for me)

1. Create a pack with ProjectE (or use an already existing one)
2. Make a new world
3. Slap down a table or give yourself a tablet
4. Dump some items into it
5. /kill yourself
6. Find your tablet / table, note that it's missing every item and all its EMC.

It might be easily solvable by relogging, but the previous version doesn't have the issue and it's easy enough just to go back one version.

**Comment by williewillus** [comment] 2016-12-01 00:20
That isn't the issue described by OP.
The bug where knowledge is lost by *death* or *teleportation* is fixed in the next version.

This is just random and there is no supporting data so I'm just going to close this until someone can actually can reproduce this WITHOUT dying or teleporting

**Closed** 2016-12-01 00:20 UTC

**Comment by Starwort** [comment] 2016-12-10 10:37
I actually found a solution anyway: unlearn any item, the EMC will return, learn it again, the table fills with previous knowledge... :)

**Comment by Starwort** [comment] 2016-12-10 10:39
PS Yashimata was correct, that was my point. The fall dmg killed me.
