### ISSUE TITLE
Tranmutation Tablet Crash

### ISSUE THREAD

**Issue by Time6628** [sinkillerj/ProjectE#712] opened 2015-05-12 12:19 UTC
On my server, when someone uses a transmutation tablet in a funny way. It suspends the server so no one can login, nothing loads(chunks, chests, etc), no mobs spawn, and you can't do anything until the server is restarted.
I'm pretty sure this is the cause:
java.lang.NullPointerException: Exception in server tick loop
	at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.writeToNBT(TransmuteTabletInventory.java:306)
	at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.func_70305_f(TransmuteTabletInventory.java:406)
	at moze_intel.projecte.gameObjs.container.TransmuteTabletContainer.func_75134_a(TransmuteTabletContainer.java:131)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1512)
	at net.minecraft.world.World.func_72900_e(World.java:1847)
	at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:446)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:945)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

Thanks,
-Time

**Comment by MaPePeR** [comment] 2015-05-12 12:35
Please use code tags or pastebin for logs like this.

**Comment by shobu9** [comment] 2015-05-12 12:43
Can you try film the crash ... Because i have tried on a server and singleplayer many times to reproduce the crash and did not happen once...

**Comment by sinkillerj** [comment] 2015-05-12 13:00
Duplicate of #513 and #350

**Closed by sinkillerj** 2015-05-12 13:00 UTC
