### ISSUE TITLE
Support understanding Applied Energistics Shaped Crafting

### ISSUE THREAD

**Issue by piotrb** [sinkillerj/ProjectE#510] opened 2015-02-19 19:48 UTC
Seems like Applied Energistics does something weird with their crafting recipes .. the crystals blink between the regular and pure and that seems to keep projecte from infering the cost of the final item.

I mean .. it'd be nice to support the "pressed" recipes too .. but those are quite finite .. easy enough to just override for the few final items. All the other miscelaneous items made via shaped are the real issue here.

**Comment by MaPePeR** [comment] 2015-02-19 20:25
These crafting ingredients, where you can use different items for crafting are not the problem. (We would not be able to add a mapping for anything that uses 'planks' if that would be the case)

AE2 uses a custom implementation for `IRecipe` which we don't understand. [repeating everything i said in: #502 ]

Also: Duplicate of #502, #301, #296, #125, #6

**Closed** 2015-02-19 20:57 UTC
