### ISSUE TITLE
Researched items in transmutation table lost until server reboot

### ISSUE THREAD

**Issue by alexgeek** [sinkillerj/ProjectE#1355] opened 2016-09-25 16:25 UTC
Occasionally all researched items disappear from the transmutation table.
Placing an item such as an iron ingot into the table comes up with researched as though it had never been learnt and no other items are available.
After rebooting the server the research comes back.
Not sure of any particular steps to reproduce, just seems to happen within an hour or so of the sever being up.

**Comment by sinkillerj** [comment] 2016-09-25 22:34
We need logs and your current Minecraft version in order to provide assistance.

**Comment by DZCreeper** [comment] 2016-09-26 05:10
Version 1.0.6B for Minecraft 1.10.2.

Forge version is 1.10.2-12.18.1.2094.

I don't have logs available ATM but I can confirm this problem occurs with a brand new world and is fixed by a server restart. I suspect there is a problem with loading player data of some sort, the table acts as though the player has never researched any items but can learn new items properly.

**Comment by bshelden** [comment] 2016-09-26 23:57
I have this sometimes as well.  Nothing special in the logs.  The extra data point I can add is I can keep tossing things into the "reset" table and eventually it all comes back.  Also, the EMC value I left in the tablet is unaffected.

**Comment by williewillus** [comment] 2016-09-27 03:19
Does it fix itself when you relog as opposed to a full restart? The interface might just be desyncing

**Comment by bshelden** [comment] 2016-09-27 03:47
The only answer I have there is disconnecting/reconnecting does not cause the issue, but a full reset always does.  So yeah, smelling desync, also smelling static variables.

**Comment by williewillus** [comment] 2016-09-27 05:38
Not static variables; Everything is stored and synced using the forge capability system but the way we display things is a bit unconventional due to the search function only being available clientside

**Comment by bshelden** [comment] 2016-09-29 03:38
Start client, connect, check table, no research.
Disconnect, reconnect.  Has research.

**Comment by williewillus** [comment] 2016-09-29 04:50
Awesome so it's just a desync

**Comment by sandalle** [comment] 2016-10-04 19:01
I've seen the same with the client sync with the following versions. Changing worlds (e.g. going to The Nether and back again) also refreshes the Transmutation Table.

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2093
- ProjectE: 1.10.2-PE1.0.6B

**Comment by williewillus** [comment] 2016-11-13 01:41
I think this is fixed by the fix for #1376
Try it out the next release (idk when that will be) and comment back if it is still an issue

**Closed by williewillus** 2016-11-13 01:41 UTC

**Comment by sinkillerj** [comment] 2016-11-13 13:50
I plan to pop out an update this week.

**Comment by sandalle** [comment] 2016-11-21 19:07
Confirmed fixed in ProjectE 1.10.2-PE1.1.0B, thank you!

**Comment by sandalle** [comment] 2016-11-21 19:12
Confirmed fixed in ProjectE 1.10.2-PE1.1.0B, thank you!
