### ISSUE TITLE
Losing patterns in transmutation table when mods update - revisited

### ISSUE THREAD

**Issue by kdx7214** [sinkillerj/ProjectE#1379] opened 2016-10-17 19:51 UTC
Was out in the hospital for a while but am back now and just tried another experiment.  I took my existing 1.10.2 server and updated ONLY the projecte jar file.  Lost all patterns known in my table/tablet.   I have a before/after set of log files - hope they help.

[logfiles.zip](https://github.com/sinkillerj/ProjectE/files/534540/logfiles.zip)

**Comment by kdx7214** [comment] 2016-10-17 20:48
Hmm, added several items to replace what was lost and suddenly everything reappeared.  Could this just be a display bug?

**Comment by williewillus** [comment] 2016-10-30 17:44
duplicate of 1376

**Closed** 2016-10-30 17:44 UTC
