### ISSUE TITLE
[1.10.2] Cant set custom emc on Hardened Clay

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1435] opened 2016-12-12 13:34 UTC
Currently attempting to set a custom emc value on Hardened Clay does nothing, even though the command goes through properly.

**Comment by williewillus** [comment] 2016-12-21 01:54
@MaPePeR do you know what's up? I see `[19:53:21] [Server thread/WARN] [ProjectE]: Overwriting fixValueBeforeInherit for minecraft:stained_hardened_clay(159:1):1111/1 to 64/1` in the log on reload. the entry makes it into custom_emc.json properly though

**Comment by MaPePeR** [comment] 2016-12-21 07:33
That message is printed if there are multiple values set for an item before the calculation is done. 
So maybe we have a default that is not behaving properly.

**Comment by Tencao** [comment] 2016-12-21 11:38
I've found a fix for this. The problem was it was checking for all data values on stained hardened clay, instead of individual values. To fix this, change 

`"minecraft:stained_hardened_clay|*": 64,`

To

`      "minecraft:stained_hardened_clay|0": 64,
      "minecraft:stained_hardened_clay|1": 64,
      "minecraft:stained_hardened_clay|2": 64,
      "minecraft:stained_hardened_clay|3": 64,
      "minecraft:stained_hardened_clay|4": 64,
      "minecraft:stained_hardened_clay|5": 64,
      "minecraft:stained_hardened_clay|6": 64,
      "minecraft:stained_hardened_clay|7": 64,
      "minecraft:stained_hardened_clay|8": 64,
      "minecraft:stained_hardened_clay|9": 64,
      "minecraft:stained_hardened_clay|10": 64,
      "minecraft:stained_hardened_clay|11": 64,
      "minecraft:stained_hardened_clay|12": 64,
      "minecraft:stained_hardened_clay|13": 64,
      "minecraft:stained_hardened_clay|14": 64,
      "minecraft:stained_hardened_clay|15": 64,`

**Comment by williewillus** [comment] 2016-12-21 16:34
i mean, even if the * is being used it should still be overridden by later custom emc stuff, so the fix is a bandaid at best

**Comment by MaPePeR** [comment] 2016-12-21 16:42
Yea, i introduced that problem with #1254.

The problem is, that for the wildcard-setemc to work you need to know all the possible metadata values, but you only can estimate these when all the recipes have been collected. So i did delay the set-value for wildcard entries until shortly before the calculation is done. This has the side effect of overwriting all other values that are set.

**Comment by williewillus** [comment] 2017-11-15 18:14
fixed in 1.12

**Closed by williewillus** 2017-11-15 18:14 UTC
