### ISSUE TITLE
Ender IO not working with Energy Condenser MK2

### ISSUE THREAD

**Issue by Zettt** [sinkillerj/ProjectE#1353] opened 2016-09-24 20:21 UTC
Extracting items (and I think inserting) is not working with Ender IO. Minecraft version 1.10.2. Playing on FTB Unstable.

**Comment by MaPePeR** [comment] 2016-09-24 20:36
I think in the 1.10 version you have to use the bottom and top side to input/extract.

This is a duplicate of #1346 

Still don't know why we cannot support this anymore, though. :/

**Comment by Zettt** [comment] 2016-09-24 20:59
Yes, possibly related. Tested, and confirmed. Extracting from the bottom works. And inserting from side and top. Thank you!

**Closed** 2017-04-30 03:16 UTC
