### ISSUE TITLE
Destruction Catalyst error

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#751] opened 2015-05-26 23:48 UTC
I was recently using the Destruction Catalyst on my server, when suddenly I encountered an internal error and a disconnect. Here's the error log from the console
http://pastebin.com/W0Sv6PAA

**Comment by sinkillerj** [comment] 2015-05-27 00:13
Duplicate of #744

**Closed by sinkillerj** 2015-05-27 00:13 UTC
