### ISSUE TITLE
Transmutation Tablet search bar crashes client

### ISSUE THREAD

**Issue by QuantumManiac** [sinkillerj/ProjectE#480] opened 2015-02-10 02:24 UTC
when you click on the search bar and type in, it crashes your client. Using latest version (which else?)

**Comment by QuantumManiac** [comment] 2015-02-10 04:58
Crashlog: http://pastebin.com/w4ukUJVY

**Comment by sinkillerj** [comment] 2015-02-10 05:04
Duplicate of  #459

**Closed by sinkillerj** 2015-02-10 05:04 UTC
