### ISSUE TITLE
Item with no value shift-clicked into AMR causes crash

### ISSUE THREAD

**Issue by hotrods20** [sinkillerj/ProjectE#996] opened 2015-09-09 20:25 UTC
Accidentally shift-clicked an item with no EMC value into an Anti-Matter Relay MK3 and the game crashed with a can't divide by zero bug.
EDIT: Looked at code. It only checks if the EMCMapper has the item. It doesn't check if the EMC value is zero.

**Comment by williewillus** [comment] 2015-09-10 01:22
what version, latest?

**Comment by hotrods20** [comment] 2015-09-10 01:22
Yeah, using the latest as of this morning. Still happens.

**Comment by MaPePeR** [comment] 2015-09-11 13:50
Can not reproduce this with current master. Also duplicate of #898

**Closed** 2015-09-17 01:48 UTC
