### ISSUE TITLE
LAN Packets are buffered strangely, causing crashes

### ISSUE THREAD

**Issue by Bubbet** [sinkillerj/ProjectE#1100] opened 2015-11-30 02:47 UTC
I was trying to play on a "open to LAN" server and came across so many bugs the mod was unplayable. If you were to look at obsidian it would crash your entire mine craft, If you opened the energy condenser it would give you an internal server error and boot you, things like that. You should take a look at this.
I was playing 1.8 1.1.1 But we tested all of the currently released 1.8 versions and all have the same issue. Just figured id enlighten you, as i don't imagine you do much testing in a LAN server.

**Comment by sinkillerj** [comment] 2015-11-30 04:29
There is not much we can do for you without logs of those crashes, some of them even sound like things unrelated to ProjectE. In general I stand with other modders that open to lan is no substitute for a proper server, and that running both has very little extra overhead, so little support is provided, but we can at least look over the logs.

**Comment by Bubbet** [comment] 2015-11-30 04:31
I understand that, and could supply logs. Its just more convenient to use open to LAN. Everything was working fine with an external server though, or so it seemed.

**Comment by Bubbet** [comment] 2015-11-30 04:35
[crash-2015-11-29_11.57.54-client.txt](https://github.com/sinkillerj/ProjectE/files/46928/crash-2015-11-29_11.57.54-client.txt)
That should be for the obsidian crash when holding a philosopher stone.

**Comment by Bubbet** [comment] 2015-11-30 04:44
I cant seem to find the other logs involving the condenser crashing etc. So ill attempt to recreate with just projectE and forge installed.

**Comment by Bubbet** [comment] 2015-11-30 05:30
The connecting player. (the one that gets kicked for an internal server error)
[Uploading fml-client-latest.log.txt…]()
[Uploading fml-junk-earlystartup.log.txt…]()
[Uploading latest.log.txt…]()


The host player.
[Uploading fml-client-latest.log.txt…]()
[Uploading fml-junk-earlystartup.log.txt…]()
[Uploading latest.log.txt…]()

**Comment by Bubbet** [comment] 2015-11-30 05:31
Lol sorry about closing it. That is logs of both players, Forge and ProjectE are the only things installed.

**Comment by williewillus** [comment] 2015-11-30 06:01
The first crash log you posted does not seem to be our fault (there is a class with package "mca.core..." which is not what we are. 

The six links you posted above are all links back to this ticket, so I have no info here :p

**Comment by Bubbet** [comment] 2015-11-30 06:05
Perhaps you can direct me to where i can find this info? I can recreate the bug.

**Comment by williewillus** [comment] 2015-11-30 06:06
I mean, try uploading those six logs again because I can't see any of them (links are broke)

**Comment by Bubbet** [comment] 2015-11-30 06:32
Ah alright here.
Connector.
[fml-client-latest.log.txt](https://github.com/sinkillerj/ProjectE/files/46990/fml-client-latest.log.txt)
[fml-junk-earlystartup.log.txt](https://github.com/sinkillerj/ProjectE/files/46991/fml-junk-earlystartup.log.txt)
[latest.log.txt](https://github.com/sinkillerj/ProjectE/files/46992/latest.log.txt)
Host.
[fml-client-latest.log.txt](https://github.com/sinkillerj/ProjectE/files/46997/fml-client-latest.log.txt)
[fml-junk-earlystartup.log.txt](https://github.com/sinkillerj/ProjectE/files/46998/fml-junk-earlystartup.log.txt)
[latest.log.txt](https://github.com/sinkillerj/ProjectE/files/46999/latest.log.txt)

**Comment by williewillus** [comment] 2015-11-30 06:41
Host's log has ```java.io.IOException: An established connection was aborted by the software in your host machine```

Some googling around says two things
1. Multiple MC instances are trying to run on the same port (unlikely)
2. A firewall on the host's computer is killing MC's connection. (likely)

Recheck your firewall on the host side.

Can you give me exact steps to reproduce? If I can't reproduce it then it's likely a localized/hardware issue, and you should try using a dedicated server.

**Comment by Bubbet** [comment] 2015-11-30 06:43
Actually the multiple instances on one port could be it, but that cannot be the only reason for this, as it crashed other computers running different instances. I run the two instances side by side for this testing here, i don't really wanna get up to go to my PC so Ive just used my laptop.

**Comment by Bubbet** [comment] 2015-11-30 06:45
The exact steps for a reproduce would be:
Have host open game to lan.
Have connector connect and try opening a energy collector mk1 or energy condenser. 
Or for the other crash you take a philosopher stone and look at obsidian.
It really isn't hard to reproduce.
Like i said it pretty much breaks everything. Yet everything functions fine on a proper external server.

**Comment by williewillus** [comment] 2015-11-30 06:55
I can't reproduce the obsidian thing, but reproduced the other one. Thanks!

**Comment by Bubbet** [comment] 2015-11-30 06:57
Well the obsidian one did have a number of different mods added in, i didn't try reproducing it with just ProjectE Ill see if i can now.

**Comment by Bubbet** [comment] 2015-11-30 07:02
[ObbyCrash.txt](https://github.com/sinkillerj/ProjectE/files/47019/ObbyCrash.txt)
I got this, to reproduce you'd have to be on the connected. The host seems stable when looking at obby.

**Comment by williewillus** [comment] 2015-11-30 07:04
Oh, that's just because it calls a forge function that is newer than what you have installed, update forge.
I'll investigate the packet thing

**Comment by Bubbet** [comment] 2015-11-30 07:06
Ah alright, well I'm glad i could point stuff out. Hopefully you guys fix stuff. :D
I should be getting emails for this thing here if you need me to reproduce more stuff.

**Comment by williewillus** [comment] 2015-11-30 07:16
This might be a forge/vanilla lan bug, because the entirely wrong packets are being sent for no reason in LAN but not in dedicated server.

**Comment by Bubbet** [comment] 2015-11-30 14:39
Well if that's the case it'll have to be up to you to tell them, I wouldn't know what I'm talking about. Even though eventually I'd like to.

**Comment by MaPePeR** [comment] 2015-11-30 14:59
> Host's log has java.io.IOException: An established connection was aborted by the software in your host machine

I think the host isn't the problem then.This says that the Connector disconnected unexpectedly

Looking at the Connector log there is an Exception-Stacktrace that contains our code directly after this message: 

>[23:24:59] [Client thread/DEBUG] [ProjectE/]: Clearing offline data cache in preparation to load online data

so i don't really think its a vanilla bug. (In the past it has always been our fault)

**Comment by williewillus** [comment] 2015-11-30 16:06
Yeah I tried it a bit more and it seems like the client's fault. The packethandler for SyncEmcPKT keeps being called no matter what kind of packet the server/host sends out. Interestingly, SyncEmcPKT has discriminator id 0 in our net handler so maybe the discriminator is getting corrupting somehow

**Comment by williewillus** [comment] 2015-11-30 16:09
The "clearing offline cache" relates to Transmutation knowledge and is completely serversided so I don't think it's related in this case (booting clients, etc.)

**Comment by MaPePeR** [comment] 2015-11-30 16:15
Strange

**Comment by williewillus** [comment] 2015-12-21 05:58
May be a forge bug http://www.minecraftforge.net/forum/index.php/topic,35556.0.html

**Comment by williewillus** [comment] 2016-02-15 16:06
Fixed by forge

**Closed by williewillus** 2016-02-15 16:06 UTC
