### ISSUE TITLE
[BUG] Inequivalent exchange <1

### ISSUE THREAD

**Issue by DemonfangArun** [sinkillerj/ProjectE#1765] opened 2018-10-28 11:00 UTC
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.3.1B

Exact Forge version: 14.23.4.2768

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): n/a

Upon setting inequivalent exchange to 0.2, items with an EMC of 1 still burn for 1 EMC. The expected behavior would be for them to be worthless when burning. Since in most modpacks setting up a turbo fast cobblestone generator is trivial, being able to just feed cobble into a condenser endlessly would largely defeat the inequivalent exchange setting. It is still desirable to have cobble have an EMC value for pulling out.

Proposed solutions (changeable in config):
1-Make any item for which the burn EMC is <1 burn for 0 (essentially act like a trash bin). I had heard that this is how it worked, but in reality it doesn't.
2-Make it so that the burn EMC can be set manually (this would be useful for defeating compressed cobblestone and other compressed blocks)
3-Add fractional EMC (unlikely, and would have to be combined with 1 or 2 to prevent easily getting EMC)
4-A combination of the above

**Comment by sinkillerj** [comment] 2018-10-28 14:11
Duplicate of #1745

**Closed by sinkillerj** 2018-10-28 14:11 UTC
