### ISSUE TITLE
Free EMC forever.

### ISSUE THREAD

**Issue by Asphodan** [sinkillerj/ProjectE#1218] opened 2016-04-29 02:09 UTC
Steps to replicate:

1. Open up a Transmutation Table/Tablet.
2. Place an item into the _unlearn_ slot.
3. Shift-click the item, turning it into EMC.  Notice a RED 0 in the lower-right corner of the item.
4. Left-click the item, picking it up. Place item into your inventory, manually. No shift-clicking or other assisted moves.
5. Manually place this RED0-Item into an Energy Condenser; left clicks and no manual placing. Receive the EMC again.

This starts a fairly easy EMC doubling loop.

**Comment by Robotia** [comment] 2016-04-29 02:20
Which version are you on? 1.7.10 or 1.8.9?
So the stack size is 0? I know there is a bug with MinecraftForge 1.7.10 where you can have items with stacksize 0 in your inventory, this was fixed in Thermos (https://github.com/CyberdyneCC/Thermos) though.

**Comment by Asphodan** [comment] 2016-04-29 03:42
I'm on the 1.8.9 version. I downloaded it, oh, two days ago or so.

Additionally, I'm running a "stock" version of FTB Unstable 1.8.9.

**Comment by MaPePeR** [comment] 2016-04-29 20:18
To fix the free EMC should be easy. A stacksize check [here](https://github.com/sinkillerj/ProjectE/blob/MC18/src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java#L114). But not sure what is actually creating the 0-stack.

**Comment by Robotia** [comment] 2016-04-30 04:33
@MaPePeR I believe there is a related issue in 1.7.10 which might help you understand the cause. I have named these things "virtual items". They are fake but never disappear because Forge does not try to remove items with a 0 stacksize in the inventory. 

I noticed it when I was using an energy condenser. I was trying the classic "have another player keep it open while you break it" dupe, and the items produced were virtual items. I put the virtual item manually into a condenser and it was converted to the EMC of one of its type. I'm not sure what can be done to solve this though :confused:

**Comment by MaPePeR** [comment] 2016-04-30 05:54
The GUI should close automatically, when you destroy the block....

**Comment by Robotia** [comment] 2016-04-30 11:50
That's what I thought, but it doesn't seem to in 1.7.10 o.o

**Comment by Robotia** [comment] 2016-05-09 02:06
Should this be closed now?

**Closed** 2016-05-09 03:19 UTC
Labels: 1.8
