### ISSUE TITLE
crash when loading due StackOverflowError

### ISSUE THREAD

**Issue by ovear** [sinkillerj/ProjectE#1176] opened 2016-02-08 07:32 UTC
minecraft version 1.7.10 just install projectE

log is here

http://pastebin.com/UJHd5Yjk

**Comment by sinkillerj** [comment] 2016-02-08 14:36
What language is your Minecraft client set to?

**Comment by ovear** [comment] 2016-02-08 17:17
Simplify Chinese

**Comment by sinkillerj** [comment] 2016-02-08 21:30
Duplicate of #1171

**Closed by sinkillerj** 2016-02-08 21:30 UTC
