### ISSUE TITLE
Abyss Helmet Ability Doesn't Activate

### ISSUE THREAD

**Issue by Gushousekai195** [sinkillerj/ProjectE#2011] opened 2020-05-06 22:29 UTC
ProjectE-1.15.2-PE1.0.3B

1.15.2-forge-31.1.62

Steps to reproduce:

1. Craft Abyss Helmet
2. Wear Abyss Helmet
3. Press Left Shift+x

I expected the helmet's night vision ability to activate.

But, nothing happens.

I would suggest checking on the abilities of the other pieces of gem armor, too.

**Comment by pupnewfster** [comment] 2020-05-06 22:42
Going to mark this as fixed in dev as I cannot reproduce it in dev, and I seem to recall fixing it a few days ago when I was last working on the code, though I can't find the specific commit.

**Closed** 2020-06-12 03:12 UTC
Labels: Fixed in Dev
