### ISSUE TITLE
[GLITCH] Inventory Tweaks UNLIMITED POWAAAA

### ISSUE THREAD

**Issue by RiptideTV** [sinkillerj/ProjectE#874] opened 2015-07-28 02:45 UTC
Using the mod Inventory Tweaks, you can scroll wheel to move single items in inventories. In the Transmutation table, however, you can scroll wheel on an item and the transmutation table will do something very strange. It will say "Learned" though it actually doesn't, but what it does do, is give you the EMC for the item used. A.K.A UNLIMITED POWAAAAAAA.

**Comment by sinkillerj** [comment] 2015-07-28 04:04
Dupe of a dupe of a dupe, the EMC is never actually added, this is a client side issue only.

**Closed by sinkillerj** 2015-07-28 04:04 UTC
