### ISSUE TITLE
Client crash on login due to alchemical bags

### ISSUE THREAD

**Issue by Drethic** [sinkillerj/ProjectE#1192] opened 2016-02-19 18:21 UTC
We have ProjectE 1.7.10-PE1.9.5 installed.  While trying to clear out an area one of my users put items into different alchemicals bags.  Then he stored all those bags in a Tinkers Construct (TConstruct-1.7.10-1.8.8.build991) knapsack.  This is the errors he receives when logging in (from fml-server-latest):
http://pastebin.com/d0fkEciB

That is from his fml-client-latest file.
http://pastebin.com/VpKUsG6h

**Comment by williewillus** [comment] 2016-02-19 18:35
is it reproducible every time?

could you send me his player.dat file?

**Comment by Drethic** [comment] 2016-02-19 18:41
Yes, every time he's tried to log in since logging out yesterday when he put the alchemical bags inside the knapsack.

Here is his player.dat file from the server:
https://www.dropbox.com/s/tnqqwroli3x99gs/9c79605c-7c22-4ff8-ab96-7e55257b43ef.dat?dl=0

That link will expire on 2/22.

**Comment by williewillus** [comment] 2016-02-19 19:00
which color bags were put in the knapsack?

**Comment by MaPePeR** [comment] 2016-02-19 19:05
i guess it crashes because of max recursion depth or nbt max byte size. i think we had this issue before. 

I think the only solution is to remove the bag from the bag (ha!) using some sort of nbt editor

**Comment by Drethic** [comment] 2016-02-19 19:13
He's not sure which ones he put in, however, here are the items id's for the different items.

Knapsack: 5411
Alchemical Bags:
White 5198
Orange 5198:1
Magenta 5198:2
Light Blue 5198:3
Yellow 5198:4
Lime 5198:5
Pink 5198:6
Gray 5198:7
Light Gray 5198:8
Cyan 5198:9
Purple 5198:10
Blue 5198:11
Brown 5198:12
Green 5198:13
Red 5198:14
Black 5198:15

I'm also going through his NBT data to see if I can do what @MaPePeR suggests.

**Comment by williewillus** [comment] 2016-02-19 19:13
but our bags don't store any info in the stack, it's all stored in the IEEPs separately, so there shouldn't be a data overflow

**Comment by MaPePeR** [comment] 2016-02-19 19:28
you are totally right. forgot about that.

**Comment by Drethic** [comment] 2016-02-19 19:57
Update:
I completely emptied the TConstruct -> Knapsack key
I removed all entries from Inventory that were alchemical bags

Neither helped.  Looking at the contents of each bag now.

**Comment by sinkillerj** [comment] 2016-02-20 01:58
Closing as it seams Advanced Genetics is at fault, if it turns out that we do something odd that causes it freak out feel free to comment and ill reopen.

**Closed by sinkillerj** 2016-02-20 01:58 UTC
