### ISSUE TITLE
Transmutation tables

### ISSUE THREAD

**Issue by LoZio95** [sinkillerj/ProjectE#1420] opened 2016-12-01 11:43 UTC
Transmutation tables forgets the Items when I get back from another dimension :(
1.10.2
ProjectE-1.10.2-PE1.1.0B.jar

**Comment by sinkillerj** [comment] 2016-12-01 12:01
Duplicate of a duplicate of a duplicate. Will be fixed in the next version.

**Closed by sinkillerj** 2016-12-01 12:01 UTC
