### ISSUE TITLE
Transmutation Tablet Allows Interaction With Its Item While GUI is Open

### ISSUE THREAD

**Issue by Darkosto** [sinkillerj/ProjectE#2195] opened 2022-04-29 18:54 UTC
Hello!

After some testing with the mod, I've discovered the Tablet item can be interacted with while its GUI is open. This means you can put the Tablet inside of the Transmutation GUI and effectively lose the tablet when the GUI is closed. This may not be a big problem with default recipes, however, any situation where the tablet is gated may soft-lock a player. Is it possible to not allow interaction with the Tablet in your inventory/hotbar while the GUI is being is interacted with?

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.0.1

Exact Forge version: 40.1.0

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Put Transmutation Tablet in your hot bar
2. Open the Tablet GUI
3. Click on and move the tablet within your inventory or the Project E Tablet GUI

What I expected to happen:

Based on prior versions of this mod, the item was locked to the slots when the GUI was open.

What happened instead:

I was able to lose the tablet after using it in the GUI

Thank you very much! Let me know if I can help further,
Darkosto

**Comment by pupnewfster** [comment] 2022-04-29 21:18
Hmm, I will need to look into this as it sounds like something broke when I was rewriting some of the validation during the port to 1.18 to fix some bugs I found that let you move it when you weren't supposed to be able to.

**Comment by pupnewfster** [comment] 2022-04-29 21:23
Just did a quick test and I am not able to reproduce this. Is this happening in single player or on a dedicated server? Also is it just from normally right clicking or is it from trying to change hotbar slots while opening it so that it opens on the "wrong" item (which is one of the things my rewrite is supposed to further prevent)?

**Comment by Darkosto** [comment] 2022-04-30 02:13
Oh interesting! I can look further into which mod may be causing a strange interaction with it. I'm able to open the GUI and then right-click to pick the item up (as you would when crafting in a grid). When I do this, I can actually drag the item and throw it out of my inventory too. This was on a Single Player game.

I'll get back to you if I can narrow down what the interaction may be caused by,

**Comment by pupnewfster** [comment] 2022-04-30 14:41
Hmm interesting, if I had to guess it probably is one of the mouse tweaking mods that exist presuming you have one installed.

**Comment by Darkosto** [comment] 2022-05-06 18:28
Thanks for your patience while I dig into this further. It looks like the issue is instigated when the InventoryFree mod is installed. I've posted an issue over on their tracker: https://github.com/kirderf1/InventoryFree/issues/10

**Comment by pupnewfster** [comment] 2022-05-06 18:47
Closing this as after doing a brief glance at their code (https://github.com/kirderf1/InventoryFree/issues/10#issuecomment-1119918435) it looks like the issue is entirely on their end.

**Closed by pupnewfster** 2022-05-06 18:47 UTC

**Comment by Darkosto** [comment] 2022-05-06 18:59
Thanks for checking this out!
