### ISSUE TITLE
the 1.14 release seems to have trouble auto assigning emc values with larger mod packs.

### ISSUE THREAD

**Issue by gravysamich** [sinkillerj/ProjectE#1940] opened 2019-12-05 11:43 UTC
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.14.4-PE1.0.0B.jar

Exact Forge version: forge-1.14.4-28.1.96 (when i have time i will be testing on forge-1.14.4-28.1.99)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash

Steps to reproduce:

1. install projecte
2. check to see if basic things have emc values
3. sometimes they do sometimes they dont

What I expected to happen: i expected not to have to manually set emc values for thousands of objects. some of them are as basic as a diamond block too. i figured i would have to do this for modded items, but not for unmodded things. i even have to re add emc values to things from projecte

What happened instead: large chunks of items don't have emc values. sometimes they do though. it is inconsistent. the only way to guarantee that they do have an emc value is to put it in manually.

**Comment by pupnewfster** [comment] 2019-12-05 15:32
Is this a pack that you made or one that is on curse? Wondering in terms of having a simpler way to test reproducing it. Also it would probably be helpful to see your latest (or maybe debug) log. Also does running `/reload` make any difference, part of me is wondering if it for some reason doesn't have all the information yet when it is doing the calculations.

**Comment by MaPePeR** [comment] 2019-12-05 17:08
Might also be a result of other mods adding recipes that invalidate emc values.

**Comment by gravysamich** [comment] 2019-12-06 04:46
i am using a custom pack unfortunately so reproducing it might be difficult without my mod list. 

also, yes the "/reload" command does make a difference. that is actually part of the reason i am making this issue report. when i load up a new world, some items will have emc and others won't. when i run the command,some that do might lose their emc values and some that don't might gain them.

i am attaching the latest log as it is too big to use the free version of pastebin for.

also, here is an option for reproducing the issue. probably really uncool of me to do it this way, but i uploaded my mods folder to my google drive. i am not trying to redistribute these mods or take credit for them, just make making testing this issue easier.

[mods.zip](https://drive.google.com/file/d/12eyZAIxGcOKSDyuTgaxd-sz6M9_BXeCW/view?usp=sharing)
 
[latest.log](https://github.com/sinkillerj/ProjectE/files/3930416/latest.log)

**Comment by pupnewfster** [comment] 2019-12-06 05:38
From your log
```
Exception during Mapping Collection from Mapper moze_intel.projecte.emc.mappers.CraftingMapper. PLEASE REPORT THIS! EMC VALUES MIGHT BE INCONSISTENT!
java.lang.NullPointerException
	at com.tfar.unstabletools.item.ItemDivisionSign.damage(ItemDivisionSign.java:61)
	at com.tfar.unstabletools.item.ItemDivisionSign.getContainerItem(ItemDivisionSign.java:55)
	at moze_intel.projecte.emc.mappers.CraftingMapper.addMappings(CraftingMapper.java:84)
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:103)
	at moze_intel.projecte.emc.EMCReloadListener.func_195410_a(EMCReloadListener.java:23)
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16)
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$6530/79710837.run(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$7778/479839738.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1432)
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:436)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:75)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:745)
```

I would try disabling unstable tools and see if it fixes it, if so I would try reporting an issue to them linking back to here, because they seem to be crashing from `stack.getItem().getContainerItem(stack)`, after we check `stack.getItem().hasContainerItem(stack)` and they return they do setup. Seems to be caused by this [line](https://github.com/Tfarcenim/Unstable-Tools/blob/1.14.x/src/main/java/com/tfar/unstabletools/item/ItemDivisionSign.java#L61) and them calling `getTag` instead of `getOrCreateTag`

**Comment by pupnewfster** [comment] 2019-12-06 05:43
cc: @Tfarcenim

**Comment by gravysamich** [comment] 2019-12-06 07:38
wow, i can't believe it was just that 1 mod that was throwing a wrench into the works. i removed it and everything seems to be working as intended now. 

seriously, a huge thank you for helping me with this!

**Comment by pupnewfster** [comment] 2019-12-06 16:52
Closing this as I believe it has been fixed now on their end.

**Closed by pupnewfster** 2019-12-06 16:52 UTC
