### ISSUE TITLE
EMC Allocation Never Happens (Injection into Direwolf 1.7.10 pack)

### ISSUE THREAD

**Issue by abraxas** [sinkillerj/ProjectE#629] opened 2015-04-08 17:43 UTC
I tried to plug ProjectE into the otherwise stock Direwolf20 pack seen here https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.2.1

Everything seemed to work in terms of recipes, but nothing has EMC values.  Not vanilla, not ProjectE stuff, nothing.

Here's my error log: http://paste.ubuntu.com/10772804/

It appears to me that EMC values are being allocated, then immediately stripped... All this, however, happens on the tail of a File I/O error that may or may not be related.

At the end of the process, I end up with an empty mapping.cfg.  I'm not sure if that's supposed to represent the EMC values for blocks.

For head's up.  I'm working on a Macbook pro on OS X Yosemite.  I have not yet tried this in linux or windows, but can update the ticket with results to those if that turns out to be material.

**Comment by MaPePeR** [comment] 2015-04-08 18:06
The problem is this:
```
Exception in thread "ProjectE Reload EMC Thread" java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at moze_intel.projecte.emc.mappers.CraftingMapper.addMappings(CraftingMapper.java:30)
at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:31)
at moze_intel.projecte.emc.ThreadReloadEMCMap.run(ThreadReloadEMCMap.java:37)
```

line 16439

**Comment by abraxas** [comment] 2015-04-08 19:32
Is this sufficient for research on your part, or do you need any more from me?

Alternatively, does this scream of an obvious conflict that I could attempt to qualify/disqualify for you?

**Comment by MaPePeR** [comment] 2015-04-08 19:55
I think this is sufficient, thank you. 
Sadly i don't know about any way to figure out which other mod caused it. It is some kind of conflict, but its only conflicting because bad code on our side, i think.

**Comment by sinkillerj** [comment] 2015-04-08 20:33
It's def on our side, other mods are not to blame. A emergency build has been published which reverts the pull that caused this for now, however I will leave this issue open till a proper fix is in place.

**Comment by Parker8283** [comment] 2015-04-08 21:47
Never got this on my end. I'll do some testing and see if I can't fix it. Sorry to cause this.

**Comment by Parker8283** [comment] 2015-04-08 22:01
In looking into this, this actually may be a cross-mod problem. The problem is when ProjectE queries the list of Crafting Recipes, and starts going though it, someone else is modifying the list (which mod authors shouldn't be doing when the server is starting; that should be finished before you're brought to the main menu.) Considering I can't replicate this with JUST ProjectE (could others test with just ProjectE please?), I can only assume this is a cross-mod issue.

**Comment by abraxas** [comment] 2015-04-08 22:03
Just to verify (sorry on the delay), this rollback patch definitely solved the problem for me.  You're barking up the right tree.

Thanks!

**Comment by Parker8283** [comment] 2015-04-08 22:16
@abraxas The reason the rollback patch works is because in the version prior to 1.4.3 (or in 1.4.3.1 in this case) holds up the entire server process to run the EMC mapper. In 1.4.3, I tried to offload the process to another thread and let the server continue to startup/run, mostly to prevent lag when running the commands to set/reload EMC. However, in the offloading, that means the server is also doing things at the same time as ProjectE is, and some mod is screwing with the Crafting Recipes list when ProjectE is trying to read it, which mods shouldn't be altering the list during Server startup; mods should be all done with that before you're brought to the main menu. I cannot reproduce this with JUST ProjectE installed, which makes me believe that this MUST be a cross-mod conflict.

**Comment by Brycey92** [comment] 2015-04-08 23:36
@Parker8283, will the EMC mapping be offloaded to another thread in the future if the other mod is identified and its author scolded?

**Comment by Parker8283** [comment] 2015-04-08 23:38
In talking on IRC, I've heard it could be minetweaker. Haven't been able to test yet. I hope we can keep it threaded in the future.

**Comment by Parker8283** [comment] 2015-04-09 00:46
@abraxas Could I get you to add [this mod](https://www.dropbox.com/s/15uqbb8czxx6fna/WhosTouchedTheCraftingList-1.7.10-1.0.jar?dl=0) into your DW20 pack instance with ProjectE 1.4.3 please? It's a debugging mod that I wrote to help track where the problem is coming from. Run Minecraft and load up a world. Once the world is all loaded up, quit Minecraft (you may have to kill it) and post the log. You may notice MC being a lot slower than normal, and that will be my mod doing excessive logging. The log file will be rather large, but it should help to track down who is conflicting with ProjectE.

**Comment by williewillus** [comment] 2015-04-09 01:52
^I have some free time so I'm running that right now, and COFH is absolutely murdering it right now, haha
Loading for 10 mins and counting, literally worse than gregtech™ !

**Comment by williewillus** [comment] 2015-04-09 02:03
We found our culprit, MPS!
http://i.gyazo.com/cf651e035f5ad82622fdaf6d6c553582.png

**Comment by williewillus** [comment] 2015-04-09 02:29
Update: So making the mod load after numina/MPS is no use. The exact problem is...
1. ServerStartingEvent is called in the order mods are loaded. Which is alphabetically
2. ProjectE fires its event handler, which starts a thread in the background.
3. While the Mapper thread is chugging along, FML continues calling event handlers.Powersuits is further down on the list and it registers several recipes, causing a CME for the ProjectE mapper thread.

Idk how to handle this :/ 
Perhaps move the mapping to ServerStarted? anyone who writes recipes at that phase really should diaf. But I don't know how well the PE machines would handle having no EMC values for a split second.

**Comment by Brycey92** [comment] 2015-04-09 03:31
If the PE machines do have any issue with that, you could just set a boolean in ServerStarted and have the machines not tick unless the boolean is set to whatever value. Probably an easier way to go about this but hey.

**Comment by williewillus** [comment] 2015-04-09 04:28
I tried moving the call to map emc to serverStarted instead of serverStarting, and there appear to be no harmful effects in SSP.
Need more testing before we just change that though (high lag env, dedicated server, etc.)

**Comment by Parker8283** [comment] 2015-04-09 11:38
I guess during server startup, we could have the EMC mapping run on the server thread (I don't want to, but it may be the best option), then have the commands be threaded, as that was my original reason to thread this. But I'd rather mods just not add recipes during server startup.

We could also complain to MachineMuse. That's an option. Also, how did you force the mod to load after MPS and Numina?

**Comment by Parker8283** [comment] 2015-04-09 11:43
Also, we could catch any exceptions in the thread, and then sleep for x seconds, then try mapping again. Maybe that would solve the problem?

**Comment by Brycey92** [comment] 2015-04-09 12:19
Now wait, whose version of MPS is this? There are several separate maintainers who all use net.machinemuse.numina.

**Comment by Parker8283** [comment] 2015-04-09 12:23
I'm going to assume it's MachineMuse's, considering it's never been updated.

**Comment by Parker8283** [comment] 2015-04-09 13:17
Can we verify that removing MPS and Numina that it works? The culprit is actually Numina, as MPS doesn't listen for ServerStarting.

**Comment by MaPePeR** [comment] 2015-04-09 15:17
I don't think we need threading support for when the server loads. It will just increase the loading time and i'm totally fine with that.

Also consider, that at some point we planned to make emc generation a one-time thing and save the generated values to a file: that would also totally invalidate the need for threading during server start.

**Comment by Parker8283** [comment] 2015-04-09 15:31
I have noticed that in large mod packs, loading the world takes QUITE a long time. Granted, the whole reason for threading in the first place was because using the commands kicked everyone from the server due to timing out. I would love it if for the time being everything stayed threaded. People shouldn't be altering the recipe list in ServerStarting.

If, however, something needed to become unthreaded, I would rather it be when the server is starting up. However, we should keep in mind that, now that we know people are registering recipes in ServerStarting, they are getting exempted from the EMCMapping until someone reloads the EMC through the command.

**Comment by MaPePeR** [comment] 2015-04-09 15:34
Maybe we should also add some  time measurements, to figure out if its the Mapping that makes worlds load slow.

**Comment by williewillus** [comment] 2015-04-09 15:35
I don't think so, it's usually sending chunks that makes login slow for me.
But I also concur with no threaded on startup, only on command

**Comment by Parker8283** [comment] 2015-04-09 15:38
Mapping is not the slowest thing that happens on world startup, by far. But I have noticed it being a factor. It sits on "Building Terrain" for a lot longer, and when looking at the log, that appears to be the EMCMapper running.

I'd be ok with the thread being command-only. I'll write a PR right now.

**Comment by MaPePeR** [comment] 2015-04-09 15:40
@Parker8283 then please also add a log message that shows how long the mapping did run. i think that would be interesting to see.

**Comment by Parker8283** [comment] 2015-04-09 15:50
#632

**Comment by MaPePeR** [comment] 2015-04-09 16:00
Thanks. (something is wrong with that PR, though, but you already noticed, i guess)

**Comment by Parker8283** [comment] 2015-04-09 16:03
633

**Comment by Parker8283** [comment] 2015-04-13 22:49
With the next version of ProjectE, this should be fixed.

**Closed** 2015-04-13 23:00 UTC
