### ISSUE TITLE
Support for mousewheel inventory interaction

### ISSUE THREAD

**Issue by Mach12** [sinkillerj/ProjectE#928] opened 2015-08-16 17:41 UTC
When transferring items in and out of the transmutation table/tablet using mousewheel (feature added by NEI iirc), shown EMC becomes async until GUI is closed then reopened, showing that the transfer worked, yet the items don't move. This gives the impression of moving EMC but not items around.

Is the ItemTransferWhateverEvent not fired when using mousewheel or something? I thought most other mods didn't do much to support mousewheel, but for some reason Project E does not.

**Comment by Mach12** [comment] 2015-08-16 17:56
I don't know if this is noteworthy, but it works when withdrawing items with mousewheel-up over an item of the table. However, placing items inside it in the same way, or interacting in any way involving mouseweel over an inventory item is malfunctioning.

**Comment by williewillus** [comment] 2015-08-16 20:57
Dupe of #318 
It's because of how our gui/container handles shift clicking currently.
NEI detects the proper slot to scroll into by "faking" a shift click then canceling it, but in our case you can't cancel the tablet eating emc you burned.
We're trying to find a way to do this, but not sure if any progress recently

**Closed by williewillus** 2015-08-16 20:57 UTC
