### ISSUE TITLE
Mod Conflict (Not Crash) w/ Lord of the Rings

### ISSUE THREAD

**Issue by thrimecia** [sinkillerj/ProjectE#1147] opened 2016-01-16 07:29 UTC
Thank you for all your work on this wonderful mod.

I have searched around to the best of my ability; insofar as I can tell there are no other reports of this conflict and this is the appropriate location to report it. My apologies in advance if I am in error.

Using the latest release for 1.7.10 (ProjectE-1.7.10-PE1.9.4.jar) from Curse, together with the Lord of the Rings mod for 1.7.10 ([1.7.10] The Lord of the Rings Mod B25.3.jar), it becomes impossible to either create or load singleplayer worlds. There is no crash; the world will attempt to load and then jump back to the title screen a few moments after 'building terrain.'

No other mods are installed.

Running:
Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1558

Given that there is no crash, I am unsure how to obtain any sort of log data to submit. If log data would be useful, I will gladly obtain and submit such given instructions on how to do so (as long as it is within my technical capability).

**Comment by sinkillerj** [comment] 2016-01-16 15:35
In your modded installation, where the folders mods config etc are, there is normally a logs folder, the logs marked latest should contain the info we need.

**Comment by thrimecia** [comment] 2016-01-16 19:48
Thank you for the quick response :)

I see two logs marked 'latest,' one short and one long. For reference, these logs are from me starting the game, attempting to create a new world, attempting to load a world created previously using a different mod configuration (which included ProjectE but not Lord of the Rings), and then exiting. While attempting to do this, the only mods installed were ProjectE and Lord of the Rings.

As one of the logs in question was too large to put on pastebin, and I couldn't figure out which parts were most relevant, I have attached them to this post as TXT files. If you would rather I copy and paste them into the text of a post or similar, just let me know and I will do so.

I am also amenable to producing other logs if helpful; I could only try to create a world, or only try to load a world, for example, if that would give you useful information.

[latest.log.txt](https://github.com/sinkillerj/ProjectE/files/93055/latest.log.txt)
[fml-client-latest.log.txt](https://github.com/sinkillerj/ProjectE/files/93056/fml-client-latest.log.txt)

Thank you again for your time.

**Comment by MaPePeR** [comment] 2016-01-16 21:57
Duplicate of #1106, i think. Fixed by #1133.

You can try [this build](https://github.com/MaPePeR/ProjectE/releases/tag/v1.9.4-craftingmapperfixes2) and see if it fixes the problem.

**Comment by thrimecia** [comment] 2016-01-16 22:42
The build you recommended, ProjectE-1.7.10-PE1.9.4-craftingmapperfixes2.jar, appears to have fixed the problem. :) I was able to both create and load worlds, and during ~30 min of playtesting I found no crashes or problems with either ProjectE or LotR items and areas.

Thank you very much for your efforts!

If you need any other logs for research purposes, etc., let me know. I will not be around tomorrow, but will keep an eye on this thread for the next couple days.

Once again, thank you. I wish you well.

**Comment by sinkillerj** [comment] 2016-01-16 23:03
We should have everything we need for now, thanks for helping us further test the new fixes.

**Closed by sinkillerj** 2016-01-16 23:03 UTC
