### ISSUE TITLE
EMC setting and projE command errors

### ISSUE THREAD

**Issue by BadLucKWyvern** [sinkillerj/ProjectE#1407] opened 2016-11-20 18:34 UTC
it was possible for me to put a lot of custom emc before to a lot of item

ive updated my minecraft and projE mod to 1.10.2

ive moved my old custom emc config file into the new server, and not working on my private MP server, trying to put some emc by looking exemple with the config file open, and i usualy have got: command failed unknown reason. so i try some more items

its working with enderzoo loots, but not with halo craft, abyssalcraft, etc: command failed unknown error.
when the few that i could change was done:
/projecte reloadEMC
Refreshing
Command failed unknown error

... whats the problem now ? i know how setting a emc and how thats work, is it working differently ? am i bugged ? it the mod bugged ? 

need a fast answer please :(

ps: sorry for my bad english

**Comment by Tencao** [comment] 2016-11-21 13:17
I am using 1.10.2 and I can confirm this is all working. What version was your old ProjectE, and also, can you list what mods you've got, forge version etc as one of the mods could be interfering with the mod.

**Comment by BadLucKWyvern** [comment] 2016-11-21 13:23
Im not on my computer y et. But when restarting the server, my friends and i lost our transmutation knowledge. But rive refreshed the EMC after trying to put some more, ans my friends knoledge was back. Idk for me because i was so angry that forced me to use the tome of knowledge...

The mod worked Well for me before 1.10.2
Idk whats happening now :/

Im using the last version of the mod on curseforge (in beta)

**Comment by Tencao** [comment] 2016-11-21 13:26
The development has had some shift in code from version to version, and it depends on what version you was using before to determine how much has changed. 

Please provide the previous minecraft version and project e version, as well as the recent forge version you're using

**Comment by BadLucKWyvern** [comment] 2016-11-21 13:27
Ill in one hour or two

**Comment by BadLucKWyvern** [comment] 2016-11-21 14:21
in 1.9.4 i had ProjectE-1.9.4-PE1.0.5B and 70 other mods
minecraft version: 1.9.4-forge1.9.4-12.17.0.1987
there was the loss of knowledge bug in this version, and indestructible redmatter furnace

right now i have:
AbyssalCraft-1.10.2-1.9.3.4       (can't put emc here, i could before)
Baubles-1.10.2-1.3.5
BBG-1.9.4-5.0.0
BetterBuildersWands-0.6.5-1.10r138+8595fc7
BiomesOPlenty-1.10.2-5.0.0.2068-universal
BloodMagic-1.9.4-2.1.0-66
Bloodmoon-MC1.9.4-1.4.1
Chameleon-1.10-2.1.8
CosmeticArmorReworked-1.10.2-v2a
DynamicLights-1.10.2                   and all his child mods (3 more)
EnderZoo-1.10-1.2.3.43                ( succefully put emc on this mod)
extrautils2-1.10.2-alpha-1.2.2
FastLeaveDecay-MC1.10.2-1.2.3
FoodExpansion1.2.4-1.10.2
Guide-API-1.10.2-2.0.2-45
halocraft-2.0-DEV-1.10.2-v1.6.183-universal      (can't put emc here, i could before)
hopperducts-mc1.9.4-1.4.8
InfernalMobs-1.10
inventorypets-1.10-1.4.8.2
IronBackpacks-1.10.2-2.2.15
ironchest-1.10.2-7.0.11.797
journeymap-1.10.2-5.2.4-unlimited
llibrary-1.7.1-1.10.2
LunatriusCore-1.10.2-1.1.2.38-universal
malisiscore-1.10.2-4.2.7
malisisdoors-1.10.2-5.1.4
Mantle-1.10.2-1.1.1
MCA-1.10.2-5.2.3-universal
mdecore-1.10.2-1.3
mobdropores-1.10.2-1.0
Pam's HarvestCraft 1.9.4-1.10.2h
ProgressiveAutomation-1.10.2-1.6.53
**ProjectE-1.10.2-PE1.0.6B**
RadixCore-1.10.2-2.1.3-universal
Random Utilities-1.9.4-3.1.1
RandomThings-MC1.10.2-3.7.7
ReapMod 1.3.3
RebornCore-1.10.2-2.8.1.64-universal
Reliquary-1.10.2-1.3.3.585
RoguelikeDungeons-1.10.2-1.5.4
SGExtraParts-1.10.2-1.1.1-6
SilentLib-1.10.2-1.1.0-23
SilentsGems-1.10.2-2.1.4-83        (can't put emc here, because a lot of items got the same name ex: silentsgems:Gem  and there is like 20+ types of gems)
SpawnerCraft 1.10.2-3.3.1
Stackie-1.10.2-1.6.0.44-universal
StorageDrawers-1.10.2-3.4.6
StorageNetwork-1.10.2-1.12.10-final
SuperOres-1.7
TConstruct-1.10.2-2.5.6b
TechReborn-1.10.2-1.4.11.96-universal
Tinkers' Addons-1.10.x-1.0.3

minecraft version:
1.10.2-forge1.10.2-12.18.2.2147

**Comment by sinkillerj** [comment] 2016-11-21 14:39
It is unlikely that your old custom EMC file will work, not only due to changes within ProjectE, but also due to the itemid mappings of your mods changing in the new MC version. The temporary knowledge wiping should be fixed in the next build.

**Closed by sinkillerj** 2016-11-21 14:39 UTC

**Comment by BadLucKWyvern** [comment] 2016-11-22 00:02
btw, after each restart of the server, my redstone emc value is back to 64, and i want to set it to 512 without losing it again
