### ISSUE TITLE
Refined tablet searching

### ISSUE THREAD

**Issue by Sourpowerpete** [sinkillerj/ProjectE#630] opened 2015-04-08 23:44 UTC
A lot of items are hard to find in the transmutation table, especially if the Tome of Knowledge is used. For example, I searched for glass (http://puu.sh/h6HlY/ace3381bcf.jpg), and regular glass just isn't on the list.  Perhaps double clicking the searchbar would do exact searches, instead of searches which have the word in them. For example, if you typed "X" in the searchbar, anything that has the letter X in it would show up, but with exact search on, only the item named "X" would appear now. Other possibilities would be searching for item ids or unlocalized names.

**Comment by sinkillerj** [comment] 2015-04-09 00:37
Duplicate of a duplicate of a duplicate. Will be addressed in the future.

**Closed by sinkillerj** 2015-04-09 00:37 UTC
