### ISSUE TITLE
[1.10.2] Transmutation Table/Transmutation Tablet Issue when entering the Nether.

### ISSUE THREAD

**Issue by Gr8umbreon** [sinkillerj/ProjectE#1459] opened 2016-12-26 00:10 UTC
I have found this bug I have described in the Title. When you have the Transmutation Table or Tablet, then you go through the Nether portal from Overworld to the Nether, all the items and EMC that you had disappears. Re-entering the Overworld through the portal does not fix anything, it remains missing from the table and tablet.

**Comment by williewillus** [comment] 2016-12-26 00:11
Duplicate of an issue that's been fixed in next release

**Closed by williewillus** 2016-12-26 00:11 UTC
