### ISSUE TITLE
SMP glitch with transmutation tables

### ISSUE THREAD

**Issue by japherwocky** [sinkillerj/ProjectE#423] opened 2015-01-24 21:30 UTC
Using ProjectE 0.2d-dev14 with NEI 1.0.3.74-universal, on an SMP server.

If I type into the NEI box to choose an item (eg, pickaxe), the table GUI shows the correct items, but clicking on the items returns something different.

The item it's returning is whatever was in that slot with nothing in the NEI box, if that makes sense.

Eg, the philosopher's stone is in the top (like 12 o'clock) slot, if I search for "iron pickaxe", the client side GUI shows the correct item, but when I pull the item out it becomes a philosopher's stone.

Probably you need to pass the actual item name/id to the server, not which slot in the GUI was clicked?

Very cool mod anyhow, thanks for your work!

**Comment by sinkillerj** [comment] 2015-01-24 21:32
Duplicate of a known issue, closing.

**Comment by japherwocky** [comment] 2015-01-24 21:33
i'm sorry i just saw #413 and came back to close this, thanks again.

**Closed by sinkillerj** 2015-01-24 21:32 UTC

**Comment by sinkillerj** [comment] 2015-01-24 21:37
It is quite alright, reports are always appreciated.
