### ISSUE TITLE
Logisitic pipe can pull anything from the Transmtute Table

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#714] opened 2015-05-13 21:55 UTC
As discovered today in the pack I run, if a provider pipe from logstic pipes is connected to the Transmutation Table, it can extract anything from the table infinity, while not consuming any emc, which can completely break the mod. The reason I report this here is it seems more like an issue with the transmute table accepting pipe requests than the mod requesting it.

**Comment by Tencao** [comment] 2015-05-13 21:56
Also recently discovered, the minecraft hopper also does this, and most likely any other piping mod, such as project red, and bluepower

**Comment by sinkillerj** [comment] 2015-05-13 22:06
Not sure how this got overlooked, I'll have it fixed in the next build.

**Comment by MaPePeR** [comment] 2015-05-14 15:44
The hopper thing is probably caused by the TransmuteTile implementing `IInventory`... 

I don't think this is intentional?

**Comment by sinkillerj** [comment] 2015-05-14 20:01
@MaPePeR That is completely intentional, the only issue here is a missing method, you are overthinking again lol.

**Comment by williewillus** [comment] 2015-05-14 22:44
Haha what was the method?

**Closed** 2015-05-17 05:17 UTC
