### ISSUE TITLE
Texture issues(Soartex textures for projectE)

### ISSUE THREAD

**Issue by BrendanP123** [sinkillerj/ProjectE#274] opened 2014-12-07 21:14 UTC
Messing about with textures and i cant seem to get them to line up, I've like tryed everything, I wonder if you guys could help? Any help would be appreciated:)

In game image
![rmfurnace](https://cloud.githubusercontent.com/assets/5054283/5332645/eeec068c-7e55-11e4-88e3-86eadecee251.png)

RM Gui
![rmfurnace](https://cloud.githubusercontent.com/assets/5054283/5332647/f6060396-7e55-11e4-8ca7-adf7be1d7c00.png)

**Comment by williewillus** [comment] 2015-06-08 03:17
Req close dupe of #466 (which has been fixed for MONTHS in #482 but still hasn't been pulled :<)

**Closed** 2015-06-08 21:30 UTC
