### ISSUE TITLE
Mod Causes Client Crash when trying to join new world

### ISSUE THREAD

**Issue by Morpheus1101** [sinkillerj/ProjectE#427] opened 2015-01-26 10:59 UTC
Crash Report @ http://www.mediafire.com/view/4clrce99gy0xtme/ProjectE.txt

All Mods used @ http://pastebin.com/qdDdAEhN

**Comment by williewillus** [comment] 2015-06-08 03:13
Req close issue was resolved since or possible duplicate of #745

**Closed** 2015-06-29 16:09 UTC
