### ISSUE TITLE
NPE in moze_intel.projecte.gameObjs.items.rings.MindStone.getStoredXP

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [sinkillerj/ProjectE#1250] opened 2016-06-07 00:57 UTC
NPE crash while viewing items in JEI.

[crash-2016-06-06_17.52.45-client.txt](https://github.com/sinkillerj/ProjectE/files/301635/crash-2016-06-06_17.52.45-client.txt)

**Comment by williewillus** [comment] 2016-06-07 00:59
4th duplicate of this issue

**Comment by Rumpelstiltskinny** [comment] 2016-06-07 01:00
then provide a release?

**Closed by williewillus** 2016-06-07 00:59 UTC

**Comment by williewillus** [comment] 2016-06-07 01:01
Because providing a release for every bug fix makes sense
