### ISSUE TITLE
Idea about talisman of repair

### ISSUE THREAD

**Issue by MyaSSSko** [sinkillerj/ProjectE#1199] opened 2016-03-06 10:45 UTC
_Sorry for my bad English, didn't practise it for too long.
_
Repairing for FREE is too OP.

What about it will gain 3 values of EMC power from different sources:
low level = low covalence dust
mid level = mid cov. dust
high level = high cov. dust or alch.coal or clein star

Cost of repair is 1 talisman emc per 3 emc of item (broken items has diff. emc value at present)

So, i have in my inventory stack of low. cov. dust, stone pickaxe and repair talisman

Talisman will eat cov.dust(or i'll should to drop it in it's inventory, like in mercurial eye), and gain, for ex. 64 low level emc

It will repair stone pickaxe to 64*3 = 192 emc.

Maths of damaged items EMC values already is in mod.

**Comment by sinkillerj** [comment] 2016-03-07 05:18
Duplicate of another discussion.

**Closed by sinkillerj** 2016-03-07 05:18 UTC
