### ISSUE TITLE
EMC values and knowledge of Portal Gun items randomly forgotten

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#1069] opened 2015-10-27 14:36 UTC
I've noticed a strange issue with iChun's Portal Gun mod and Project E, where after playing for a while the EMC values for all of the mod's items are seemingly lost (they show as having no EMC value at all).  The issue is fixed by running the reloadEMC command, but the items are erased from the transmutation tablet's knowledge.

**Comment by sinkillerj** [comment] 2015-10-27 23:46
Now that you have updated to 1.9.3h does this issue persist?

**Comment by zauberparacelsus** [comment] 2015-10-28 00:01
Not that I have seen.

**Comment by sinkillerj** [comment] 2015-10-28 00:11
Closing this for now then, if it acts up again feel free to reply and ill reopen it.

**Closed by sinkillerj** 2015-10-28 00:11 UTC

**Comment by zauberparacelsus** [comment] 2015-10-28 00:40
Well, it appears that the bug still occurs.  After updating I recorded the Portal Gun into the tablet.  Just now I checked, and it is no longer showing up on the tablet.

**Comment by MaPePeR** [comment] 2015-10-28 04:53
Bug is not fixed. The only possible fix for this is to enable pre generated emc in the configuration.

**Comment by zauberparacelsus** [comment] 2015-10-28 12:10
@MaPePeR Enabling pre-generated EMC just made the bug worse, in that it prevented the reloadEMC command from correcting the EMC.

**Comment by MaPePeR** [comment] 2015-10-28 12:27
@zauberparacelsus delete the pregenerated emc file when you have the game running and then execute the reloadEMC command.

**Comment by sinkillerj** [comment] 2015-10-28 13:06
Leaving closed as this is a duplicate of #897
