### ISSUE TITLE
ArithmeticException

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#819] opened 2015-06-30 01:48 UTC
@MaPePeR this is your domain.

http://pastebin.com/iV9J9Y1e

(Dont ask, its not my log, its from someones forum post)

**Comment by MaPePeR** [comment] 2015-06-30 06:41
That is the crash I was expecting for "item with ridiculous emc value". Might that be the case? 

I did not expect it to actually happen in the wild..

**Comment by MaPePeR** [comment] 2015-06-30 06:44
And I would be surprised if that is an 1.8-only crash

**Comment by SnapshotDesign** [comment] 2015-06-30 14:37
how should it be solved?

**Comment by MaPePeR** [comment] 2015-06-30 18:18
@SnapshotDesign is this any special modpack or something, so i could test my fix?

**Comment by SnapshotDesign** [comment] 2015-07-01 18:28
no it isn't from any mod pack. sorry

**Comment by MaPePeR** [comment] 2015-07-01 18:30
Any special mod you don't see in every pack?
Any special EMC configuration or values?

**Comment by SnapshotDesign** [comment] 2015-07-01 18:32
not really. here is a list of every mod i use.

_Skyland-Mod-1.8.jar
[1.8] moSwords v6.jar
[1.8] SkyCraft 1.0.jar
[1.8]AmberoguiaMod_v1.5.jar
[1.8]bspkrsCore-universal-7.01.jar
[1.8]DamageIndicatorsMod-3.3.3.jar
[5.0.0]EDM-1.8-dev.jar
[Forge 1.8] SpectralGuns 1.2.2.jar
1.8-zeldaswordskills-3.0.1.jar
Ad Inferos-0.2[1.8].jar
adminweapons-v2.6-mc1.8.jar
alchemyCraft-1.8-0.3.jar
AlexIILLib-1.8.jar
AnimalBikes_1.8.0_beta.jar
archimedesshipsplus-1.8-ALPHA-0.jar
Armour-Expansion-Mod-1.8.jar
Aroma1997Core-1.8-1.0.3.4.b36.jar
Aroma1997s-Dimensional-World-1.8-1.1.1.0.jar
assassincraft-MineCreed-1.3-MC-1.8.jar
AttachableGrinder-5.0.0.jar
backpack-2.0.1-1.8.x.jar
Baubles-1.8-1.1.0.0.jar
BeardedLib-1.8-1.1.jar
Better-Loading-Screen-Mod-1.8.jar
BetterLeather Mod 1.8.jar
BetterMining-1.8.6.jar
BiomesOPlenty-1.8-3.0.0.1017-universal.jar
birdmod-0.2.5.jar
Birds-Foods-Mod-1.8.jar
Blocks2Items-1.8-1.4.jar
brewingPlus-1.8-0.0.6.jar
buildingtools-0.0.5-mc1.8.jar
butterflymania-1.8-1.4.jar
C4Lib-1.8-1.0.0-universal.jar
Chisels-and-Bits-Mod-1.8.jar
CodeChickenCore-1.8-1.0.5.36-universal.jar
Colorful-Armor-Mod-1.8.jar
Configurable-Health-Mod-1.8.jar
Container Capture Mod 1.8.jar
CustomNPCs_1.8.0_beta.jar
cwm-1.8-1.2.1.jar
CyanosWonderfulWands-1.6.1-2.jar
Dark Roleplay v0.2.0.jar
decorationmegapack-1.18-1.8-1446.jar
Doge-Mod-1.8.jar
DrZharks MoCreatures Mod-8.0.0.devA-2.jar
DurabilityShow-1.8-2.0.0.jar
elementalitemsmod-5.0-MC1.8.jar
Emerald-and-Obsidian-Tools-Mod-1.8.jar
EnchantingPlus-1.8-3.1.0a1.jar
Ex-Astris-2.0.0.jar
ExNihilo2-0.26.jar
Exotic-Birds-Mod-1.8.jar
eyemod-EyeOS5.3-1.8.1.jar
Fireplace Core 2.3.2.0.jar
Flower Tea 1.8b.jar
forge_TheEpicarnoMod-1.1.4.6.jar
fruits-0.0.1.jar
FunOres-1.8-0.1.1-16-beta.jar
Gadgets_n_Goodies_mod_v1.0.1_mc_v1.8.jar
GakaisFlightTable-1.8-1.0.jar
geoactivity-2.0.jar
GiacomosExperienceSeedling1.8-1.0.jar
GiacomosFishingNet1.8-1.1.jar
GiacomosFoundry1.8-1.2.jar
GravityGun-5.0.0.jar
GreyCraft v1.0-1.8.jar
hopperducts-mc1.8-1.4.5.jar
HorseUpgradeFood-1.8-1.0.0.jar
IceCreamSandwichCreeperModv1.0.9g.jar
iChunUtil-5.4.0.jar
InventoryTweaks-1.59-176.jar
Iron-Chests-Mod-1.8.jar
KalStuff-1.8-v0.5 beta.jar
Kruuxtian Magiks-1.0.0.1.jar
LavaBoat-Mod-1.8.jar
Liquid Enchanting-1.0.jar
LuckyBlock_1-8-3_v6-0-0
Magic-Clover-Mod-1.8.jar
MakersMark-V2.0.1-MC1.8.jar
Master_Chef_v4.0-1.8.jar
MCA-5.0.6.1-1.8-universal.jar
mccurrency-1.8.1-Alpha.jar
mcrealism-0.0.1.jar
medieval_mobs-1.8.x v.a2.jar
Mini-Bosses-Mod-1.8.jar
MoreEnchantments-1.8-1.3.2.1.jar
moreore-a0.0.1R01.jar
movingworld-1.8-ALPHA-0.jar
MrCrayfishFurnitureModv3.4.7-build5(1.8).jar
my mod  0.0.4.jar
NotEnoughItems-1.8-1.0.5.96-universal.jar
OpenComputers-MC1.8-1.5.11.28-universal.jar
OptiFine_1.8.0_HD_U_D3.jar
Paintball-1.8.0v1.jar
PandorasBox-2.1.1.jar
parachutemod-1.8.0-3.1.1-23.jar
Peacefulpack 1.8.0-1.1.9.1.jar
Pixelmon-1.8-4.0.3-universal.jar
Plant-Mega-Pack-Mod-1.8.jar
pocketnether-1.8-1.3.jar
Portable Craft Bench Mod 1.8.jar
PotatoPowerCraft-0.5[1.8].jar
PowerApples-1.4.1.jar
PowerApples-1.8-1.0.0.jar
Proc-1.1-1.8.jar
ProgressiveAutomation-1.8-1.6.4.jar
ProjectBench-Update-1.8-0.4.2.jar
RadixCore-2.0.3-1.8-universal.jar
RandomThings-MC1.8-3.5.2.jar
rei_minimap
RikMuldsCore_1.2.jar
RouterReborn-1.8-2.0.0.1A-Universal.jar
Ruins-1.8.jar
ShowArmsStand-1.8-1.0_release.jar
SigurdsEpicAdventureStuff-1.0.1-mc1.8.jar
Silents-Gems-Mod-1.8.jar
SimpleBeetroot-1.8-1.0.0.jar
Singularity Mod-1.5-Universal.jar
SlimevoidLibrary-3.0.0.4-beta-1.8.jar
smeltcycle-1.0.jar
SpawnerCraft2-1.8-2.0a.jar
SpecialAttacks_1.1.4_1.8.jar
StorageDrawers-1.8-2.0.0-alpha1.jar
Talismans2-1.8-2.1.2.jar
The Consecrated Armour Mod for Minecraft 1.8.jar
The Elements Mod [1.0.5b] for Minecraft 1.8.jar
The Survivor Mod.jar
TheCampingMod_2.2.jar
Titan 1.0.0.jar
Torched-5.0.0.jar
Totem-Mod-1.8.jar
TrailMix-5.0.0.jar
TreeOres-1.8.0-1.0.jar
UnLogic II 2.0.6.0.jar
Utility-Worlds-Mod-1.8.jar
worldoverhaul-1.8-6_1.jar
wyem-1.8.0_0.0.0.jar
xaeros_minimap_v1.4.9_1.8_Forge.jar
XPTeleporters-1.8-1.0.1.jar
youtubers-mc1.8-1.7.jar
Zero Quest-v1.6.0.jar
zombieapocalypse-1.3.jar
ZombieSteak-1.8-1.0.2.jar

**Comment by kreezxil** [comment] 2015-07-05 15:15
I've got the same issue, it is crashing a dedicated server forge b1450 on startup.

Issue: ProjectE 1.8-PE1.0.0B crashes dedicated Server on startup

crash report:
https://gist.github.com/123cc6ce03436fd7180d

fml server latest:
https://gist.github.com/5d79ac36e0fb3f14f87f

**Comment by MaPePeR** [comment] 2015-07-05 15:24
Any special pack that causes this?

**Comment by TwoTailedFox** [comment] 2015-07-05 15:34
Also getting this error, but on the 1.7.10 1.7.1 version

**Comment by kreezxil** [comment] 2015-07-05 15:37
If you look at my fml server latest near the bottom around 11:04 you'll see the following

'''
[11:04:11] [Server thread/ERROR] [FML/]: Caught exception from ProjectE
java.lang.ArithmeticException: overflow: mul
	at org.apache.commons.lang3.math.Fraction.mulAndCheck(Fraction.java:643) ~[Fraction.class:?]
	at org.apache.commons.lang3.math.Fraction.addSub(Fraction.java:756) ~[Fraction.class:?]
	at org.apache.commons.lang3.math.Fraction.add(Fraction.java:713) ~[Fraction.class:?]
	at moze_intel.projecte.emc.arithmetics.HiddenFractionArithmetic.add(HiddenFractionArithmetic.java:28) ~[HiddenFractionArithmetic.class:?]
	at moze_intel.projecte.emc.arithmetics.HiddenFractionArithmetic.add(HiddenFractionArithmetic.java:7) ~[HiddenFractionArithmetic.class:?]
	at moze_intel.projecte.emc.SimpleGraphMapper.valueForConversion(SimpleGraphMapper.java:168) ~[SimpleGraphMapper.class:?]
	at moze_intel.projecte.emc.SimpleGraphMapper.generateValues(SimpleGraphMapper.java:67) ~[SimpleGraphMapper.class:?]
	at moze_intel.projecte.emc.valuetranslators.FractionToIntegerTranslator.generateValues(FractionToIntegerTranslator.java:21) ~[FractionToIntegerTranslator.class:?]
	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:84) ~[EMCMapper.class:?]
	at moze_intel.projecte.PECore.serverStarting(PECore.java:141) ~[PECore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:781) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:286) [po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
[11:04:11] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server starting event
java.lang.ArithmeticException: overflow: mul
	at org.apache.commons.lang3.math.Fraction.mulAndCheck(Fraction.java:643) ~[Fraction.class:?]
	at org.apache.commons.lang3.math.Fraction.addSub(Fraction.java:756) ~[Fraction.class:?]
	at org.apache.commons.lang3.math.Fraction.add(Fraction.java:713) ~[Fraction.class:?]
	at moze_intel.projecte.emc.arithmetics.HiddenFractionArithmetic.add(HiddenFractionArithmetic.java:28) ~[HiddenFractionArithmetic.class:?]
	at moze_intel.projecte.emc.arithmetics.HiddenFractionArithmetic.add(HiddenFractionArithmetic.java:7) ~[HiddenFractionArithmetic.class:?]
	at moze_intel.projecte.emc.SimpleGraphMapper.valueForConversion(SimpleGraphMapper.java:168) ~[SimpleGraphMapper.class:?]
	at moze_intel.projecte.emc.SimpleGraphMapper.generateValues(SimpleGraphMapper.java:67) ~[SimpleGraphMapper.class:?]
	at moze_intel.projecte.emc.valuetranslators.FractionToIntegerTranslator.generateValues(FractionToIntegerTranslator.java:21) ~[FractionToIntegerTranslator.class:?]
	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:84) ~[EMCMapper.class:?]
	at moze_intel.projecte.PECore.serverStarting(PECore.java:141) ~[PECore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:781) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:286) [po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
'''

I have a lot of the same mods as SnapshotDesign if not more! When I take out your mod, my server resumes booting as normal. So what mod causes this? Yours. :(

**Comment by MaPePeR** [comment] 2015-07-05 16:12
I know its our mods that cuases it to crash. But i also know that its caused by a combination of other mods being present.

It happens when we calculate an EMC value that is higher than what we can represent in an integer...

**Comment by MaPePeR** [comment] 2015-07-19 06:37
@sinkillerj can be closed now, i guess.

**Comment by MaPePeR** [comment] 2015-07-21 14:59
Now that this is fixed now i would really like to see a log with the latest ProjectE and the same mods that caused the ArithmeticException to occur.

**Comment by kreezxil** [comment] 2015-07-21 16:13
Challenge accepted! 

I was thinking, giacomos foundry had an issue where calculated a value so exponential that when foundry became unstable and blew up it would take out 9 chunks centered on itself and set every block in 16 squared centered on itself on fire. I had to ask the author to make a config that changed that and showed screenshots of the results.

My point is that maybe what caused the foundry to make the miscalculation might be want caused this mods to do the same. Without looking at your code but assuming it works in a way similar, if you're looking at a recipe chain to get the EMC value that might be part or might have been part of the issue as the foundry calculated its recycling values based on a recipe chain.

That said I will add this to my test server pack and see if we can generate a juicy error for you.

**Comment by kreezxil** [comment] 2015-07-21 16:15
16 == 16 chunks

**Comment by MaPePeR** [comment] 2015-07-21 16:37
The mod combination that created the error before should now show a log message about what caused it.

**Closed** 2015-07-21 20:58 UTC
Labels: 1.8
