### ISSUE TITLE
RM Furnace don't accept relay all mk's

### ISSUE THREAD

**Issue by enzoright** [sinkillerj/ProjectE#1007] opened 2015-09-15 08:30 UTC
the RM Furnace don't accept relay all mk's
in the Version 1.7.10-PE1.9.2

**Comment by williewillus** [comment] 2015-09-15 14:07
Potential duplicate of #1002

**Comment by MaPePeR** [comment] 2015-09-15 15:15
but #1002 is supposed to be fixed by #1003, which is merged into PE1.9.2

**Comment by MaPePeR** [comment] 2015-09-15 16:11
I think the problem is, that the relays don't implement the 'active push' that is needed.

**Comment by Ian-Luminus** [comment] 2015-09-27 01:28
Original EE2 behaved like this intentionally. Should just put 5 Collectors around it.

**Closed** 2015-11-01 04:42 UTC
Labels: can't-reproduce
