### ISSUE TITLE
Yeta Wrench with mod Ender IO

### ISSUE THREAD

**Issue by OmniSpecter** [sinkillerj/ProjectE#754] opened 2015-05-29 00:11 UTC
I recently noticed that while I can teach the transmutation tablet the "yeta wrench", every time I convert the item back into EMC via the tablet, it re-learns the wrench every single time as if it is a new item, and now have multiple copies of the same item in the tablet

**Comment by sinkillerj** [comment] 2015-05-29 00:12
Duplicate of  #451

**Closed by sinkillerj** 2015-05-29 00:12 UTC
