### ISSUE TITLE
Transmutation Tablet Increases EMC on Mouse Scroll Up

### ISSUE THREAD

**Issue by Lothmorg** [sinkillerj/ProjectE#1040] opened 2015-10-05 03:28 UTC
Ver: ProjectE-1.7.10-PE1.9.2
I've just upgraded from the 1.8.0 version and I've noticed that if you scroll up with the mouse cursor on an item, the EMC value in the tablet increases by that item's EMC value. I also have InfiniteInvo for more inventory rows but that was not an issue with v1.8.0 of ProjectE. The value seems to be cosmetic and does not change the "real" EMC value in the tablet.

**Comment by sinkillerj** [comment] 2015-10-05 05:17
Duplicate of a known issue, will be resolved in the next build which should be out soon.

**Closed by sinkillerj** 2015-10-05 05:17 UTC
