### ISSUE TITLE
Transmutation table bug with Immersive Engineering

### ISSUE THREAD

**Issue by Weymouth87** [sinkillerj/ProjectE#2020] opened 2020-05-26 12:49 UTC
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2 PE 1.4.1

Exact Forge version: 14.23.5.2854

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash caused.

Steps to reproduce:

1. Place creasote buckets (from Immersive Engineering) into the transmutation table.
2. Try to retrieve them from the transmutation table.
3. Recieve an empty bucket that does not stack and has a lowered emc value.

What I expected to happen:
Take the creasote buckets from the table and receive the expected item. This item is listed as having an EMC value.

As with my previous report, any support would be appreciated as this mod is being used within a pack. Apologies if this report should go to the Immersive Engineering developer, I'm not sure which mod handles this compatibility.
What happened instead:
Recieved an empty, unstackable bucket with a lowered emc value.

**Comment by sinkillerj** [comment] 2020-05-28 22:16
Duplicate of #2019

**Closed by sinkillerj** 2020-05-28 22:16 UTC
