### ISSUE TITLE
[1.10.2]Klein star recipes do not show up on JEI

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1454] opened 2016-12-22 19:16 UTC
I've noticed that the basic Klein star (Klein Star Ein) shows up on JEI recipes, however the rest do not, but the recipes do exist ingame because you can still craft them

**Comment by Ezelberoth** [comment] 2017-02-09 07:08
I have also had this bug. I came here to find out why the recipe wasn't working, I didn't know what it was, but I guess its just the display that's not working.

**Comment by zauberparacelsus** [comment] 2017-06-22 23:48
All of the Klein Stars show up for me, but only the basic one (Klein Star Ein) is craftable.  The others are unobtainable except through cheating.

**Comment by TheUnderTaker11** [comment] 2017-06-23 20:08
They do have recipes though.

**Comment by zauberparacelsus** [comment] 2017-06-23 20:10
The normal recipes are gone, that's the problem on my end.  Hit the R key to show their recipe, and there's nothing.

**Comment by TheUnderTaker11** [comment] 2017-06-23 20:35
![image](https://user-images.githubusercontent.com/16872377/27499468-925dd886-5829-11e7-8689-1cb2db874a46.png)
You said they are not craftable though, just because they don't show up in JEI doesn't mean we can't craft them.

**Comment by zauberparacelsus** [comment] 2017-06-23 20:43
I did *not* say anything about them not showing up in the JEI, that was somebody else.  I see all of them in the JEI, but only Klein Star Ein has a recipe.  The others do not, and could not be crafted when I tried doing so.

In any case, it has been half a year since the original report, and it looks to me as though the bug has changed during the releases between now and December.

**Comment by TheUnderTaker11** [comment] 2017-06-23 20:45
Well it is the original report, and the problem still persist. They are craftable, they just don't show up in JEI.
I was pointing out that your point of them being "Unobtainable except through cheating" is wrong.

**Comment by zauberparacelsus** [comment] 2017-06-23 21:09
And why exactly am I wrong?  I have tried crafting klein stars above the Klein Star Ein level, and I cannot.  If I were wrong, then I wouldn't have any trouble crafting them, and then I would not have searched the ProjectE bug tracker for Klein Star issues, and therefor I would not have said anything at all.

Dealing with bugs as both a reporter and as a project manager for a long while, one of the things that I quickly learned is that just because a particular issue doesn't occur for you, it doesn't mean that it isn't happening for other people, nor does it mean that it isn't happening the same way for others.

Or in short: they may be craftable on your minecraft installation, but on mine they cannot be crafted.

**Comment by TheUnderTaker11** [comment] 2017-06-23 22:53
Well this is the 1.10.2 version as labeled, and I have tested with the 2 most recent releases on Curse, and both work perfectly. You gave no information about what you are using, and posted a completely different problem on someone else's issue.
So either you are using an outdated build, not actually getting the bug you said (meaning it is just not showing the recipe when you hit R, and you haven't actually tried putting 4 in a crafting grid), or you need to make a new issue and give all necessary information (Forge/ProjectE/Minecraft versions).

**Comment by williewillus** [comment] 2017-06-23 23:26
Is there another mod modifying recipes in the pack?

**Comment by TheUnderTaker11** [comment] 2017-06-23 23:40
And @williewillus if you are refering to the actual issue this is about (JEI not showing the star recipes) then I can confirm that JEI never shows recipes above the first tier. It's been like that as long as I can remember for 1.10 ProjectE

**Comment by pupnewfster** [comment] 2019-02-26 19:28
Can be closed, 1.10 isn't being updated more, and this is already fixed in 1.12

**Closed** 2019-02-26 21:41 UTC
