### ISSUE TITLE
[1.8.9 BUG] After start up, cant load or create any worlds from main menu.

### ISSUE THREAD

**Issue by Bellwar** [sinkillerj/ProjectE#1159] opened 2016-01-20 21:59 UTC
Well there is no crash so here is FML logs, the end when the problem started before mods were just normally loading (found it by removing the mod from this pack (version 1.0.7)) http://www.curse.com/modpacks/minecraft/240684-magic-expansion

Please check the modlist on curse client, thanks.

http://pastebin.com/9mu1cjJ0       -FML logs

**Comment by Bellwar** [comment] 2016-01-20 22:03
Uploaded whole FML.

[fml client.TXT](https://github.com/sinkillerj/ProjectE/files/98165/fml.client.TXT)

**Comment by sinkillerj** [comment] 2016-01-21 02:14
Duplicate of #1150. Disable chisel in your ProjectE mapping config as a workaround until a fix is released.

**Closed by sinkillerj** 2016-01-21 02:14 UTC
