### ISSUE TITLE
Infinite EMC with crafting

### ISSUE THREAD

**Issue by LemADEC** [sinkillerj/ProjectE#1029] opened 2015-09-30 23:20 UTC
When crafting Klein stars, the output item comes preloaded with a 'random' amount of EMC already stored in it, hence creating free EMC. As game progress, this default values increase to reach invalid values, like storing 512000000 EMC in a Klein star zwei, or issues like this one:
ttps://gyazo.com/d87e5e9285dde46c760623d9d4b2bf72

**Comment by DZCreeper** [comment] 2015-10-01 01:39
Your link is missing the leading h causing it to be broken.

Are you using KCauldron 1.7.10-1492.155 as indicated in the other issue you created? If so you should test on a Forge environment to ensure its not Cauldron causing the issue.

**Comment by MaPePeR** [comment] 2015-10-01 03:45
Duplicate of #1022, I guess

**Closed** 2015-10-01 04:29 UTC
