### ISSUE TITLE
Red Matter Pickaxe and Dense Ores mod

### ISSUE THREAD

**Issue by Zaviv** [sinkillerj/ProjectE#483] opened 2015-02-11 19:35 UTC
The right clicking function of the red matter pickaxe doesn't remove any ores generated by the dense ores mod and Aluminum from Tinkers Construct.

Small issue jut wanted to let you know.

**Comment by sinkillerj** [comment] 2015-02-12 03:48
Duplicate of a known issue, closing.

**Closed by sinkillerj** 2015-02-12 03:48 UTC
