### ISSUE TITLE
Non-vanilla liquid emc off

### ISSUE THREAD

**Issue by junk4max** [sinkillerj/ProjectE#886] opened 2015-08-02 05:18 UTC
So i noticed in a couple different packs (madpack 2 and void) that the emc value for the liquid (melted) versions of metals is off.  The liquid version for a bucket of iron would be the cost of the bucket + the cost of one iron or 1024 emc.  The problem with this is that tinkers construct and other mods have the value of one ingot as about 1/6 of a bucket (144 mb out of 1000mb).  This can lead to a emc bug where you create a bucket of the liquid metal then convert the liquid back into the ingot form creating 6 ingots at the cost of 1 ingot.  I dont know if this is caused by the packs or not so i thought id report it anyways just in case.

**Comment by MaPePeR** [comment] 2015-08-02 05:50
This is caused by us. 

I really wondered how long it would take for someone to notice. This has been there for YEARS. 

Sadly I did not find a good way to solve this, yet. 
The problem is, that Tinkers is not 100% consistent with its fluid values. 
Molten ender pearls and obsidian behave different. 
If there is a registry that would tell me: x of something make 1 bucket of fluid that would be great.

**Comment by sinkillerj** [comment] 2015-08-02 06:00
@MaPePeR Years? Lets be slightly realistic, the mod hasn't even been around for years lol.

**Comment by MaPePeR** [comment] 2015-08-02 06:15
Well, [9 months](https://github.com/sinkillerj/ProjectE/commit/e48dc5c437de28c5208761999827cf8ac57046a5#diff-c18d6ac35a004ae118a096da927ae5b8) 
:smile:

**Comment by MaPePeR** [comment] 2015-08-02 08:28
We could try to use [`Smeltery.getSmeltingList()`](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/crafting/Smeltery.java#L202-L205) and [`LiquidCasting.getCastingRecipes`](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/library/crafting/LiquidCasting.java#L174-L177) to try to map values to the items.

Problem is, that this kind of requires working fluid mapping: At the moment, i'm not happy with giving Fluids an EMC/Bucket value because, how the mapper is written right now, it would round that value down and then be very inaccurate.

**Comment by MaPePeR** [comment] 2015-09-04 13:53
Fixed by #984 by manually defining the fluid conversions.

**Closed** 2015-10-30 17:13 UTC
