### ISSUE TITLE
PE1.1.1 MCv1.8 - Can't add custom emc through hand.?

### ISSUE THREAD

**Issue by koalalord9999** [sinkillerj/ProjectE#1112] opened 2015-12-16 09:54 UTC
https://youtu.be/rAIAgQco_B0
Video shows the issue.
I'm not really sure what the problem was, I used TAB to auto fill (at the end, still didn't work)

**Comment by MaPePeR** [comment] 2015-12-16 13:06
You would need to provide the log that is generated when executing the command. But i think this is a duplicate of #1089 
There is a fix, but i think it has not yet been released.

**Comment by sinkillerj** [comment] 2015-12-16 17:43
Known issue that will be fixed in the next version.

**Closed by sinkillerj** 2015-12-16 17:43 UTC
