### ISSUE TITLE
Transmutation Tablet Forgets

### ISSUE THREAD

**Issue by traikanossi** [sinkillerj/ProjectE#668] opened 2015-04-22 00:53 UTC
The transmutation tablet is forgetting non-host players in LAN party. So far it happens when the server goes down, and when the player changes dimensions. Sounds like the data is being stored on the client instead of the server.

**Comment by sinkillerj** [comment] 2015-04-22 03:28
Duplicate of #627

**Closed by sinkillerj** 2015-04-22 03:28 UTC
